ruby-grape/grape

lib/grape/dsl/routing.rb, spec/grape/dsl/routing_spec.rb
Hi, I've started to implement routing specs and have some questions.
Routing module is using "nest" method from API class, I think this coupling between is not quite necessary. I get rid of this class, the only thing what it is doing is calling provided block (name_inheritable methods) then making instance_eval of passed block as parameter - so I did the same. 
However, side effect of "nest" method is reset_validations! method (from Grape::DSL::Validations module) and I'm not if I should mimic it's behaviour too. 
Second thing, method "versions" suggest that we could expect probably an array of versions, but it keeps just latest defined version. Maybe we should change it in some way?
=> Version specs

CHANGELOG.md, README.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
Hashie::Mash for declared params
=> Close #797

CHANGELOG.md, README.md, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/values.rb, spec/grape/validations/params_scope_spec.rb, spec/grape/validations/validators/values_spec.rb
I added some regression tests and avoid `to_a`-ing the `Range` at all. What do you think?
=> Fix for #881

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/dsl/routing.rb, spec/shared/versioning_examples.rb
Please refer https://github.com/intridea/grape/issues/898. I haven't really understood in depth how Grape works internally, but I think this should solve the problem. I would really appreciate if you could give some feedback. 
I haven't documented this PR since I'm not sure if this is the correct fix. After I receive some feedback, I'll document this PR. Thanks!
=> add support for scoped callbcaks within a version block

CHANGELOG.md, UPGRADING.md, lib/grape.rb, lib/grape/dsl/parameters.rb, lib/grape/exceptions/missing_group_type.rb, lib/grape/exceptions/unsupported_group_type.rb, lib/grape/locale/en.yml, lib/grape/validations/params_scope.rb, spec/grape/api_spec.rb, spec/grape/validations/params_scope_spec.rb, spec/grape/validations/validators/values_spec.rb, spec/grape/validations_spec.rb
Made it so groups with required params will demand a type to be set to Array or Hash, errors otherwise (made a new exception for that).
Covered with some tests, also had to modify several existing tests to support this.
=> Make the type in group of required params required (#722)

CHANGELOG.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, spec/grape/validations_spec.rb
Without these changes the `using` does only work for `requires` and not with `optional` parameters. This restriction is currently *not* documented.
The feature / fix is required to provide a more complete DRY approach when using `grape-swagger` and `grape-entity`. With these changes, one can document the possible fields and values, e.g. when using `PATCH` update, without requiring them to be present.
=> Added support for `optional` param documentation with `using`

CHANGELOG.md, lib/grape.rb, lib/grape/exceptions/invalid_message_body.rb, lib/grape/locale/en.yml, lib/grape/middleware/formatter.rb, lib/grape/parser/json.rb, lib/grape/parser/xml.rb, spec/grape/exceptions/body_parse_errors_spec.rb
Please see issue #904 for a more detailed description. The spec with content_type `application/json` fails and is not processed by `rescue_from :all`.
=> Invalid body parse error not rescued by handlers

CHANGELOG.md, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/allow_blank_spec.rb
=> Fix allow_blank supporting DateTime/Date

CHANGELOG.md, lib/grape/validations/validators/coerce.rb
=> Fix:  toplevel constant DateTime referenced by Virtus::Attribute::DateTime

CHANGELOG.md, lib/grape/validations/validators/default.rb, spec/grape/validations/validators/default_spec.rb
apply defaults for inner params only if parent param is present
fixes #615 (see for more info)
/cc @dblock  take a look
=> fix weird behaviour for optional groups with default params

CHANGELOG.md, lib/grape/dsl/parameters.rb, spec/grape/validations/validators/presence_spec.rb
Operate on a cloned Hash when specifying `presence: true` for parameters to prevent issues with re-used entities. Includes spec and the minor fix.
Should be self explaining this time :)
=> Fix: Operate on a cloned Hash when specifying param presence

lib/grape/dsl/parameters.rb, spec/grape/dsl/parameters_spec.rb
- Add missing parameters specs
- Replace single line #group method with alias_method call
- Add comment that explains what #use method does
This is related to #874 even though name of the issue is misleading - these are not routing specs.
=> Add missing parameters specs.

README.md
Minitest 5.0 renamed `MiniTest::Unit::TestCase` to `Minitest::Test`.
=> Update README with new MiniTest base class

CHANGELOG.md, README.md, lib/grape/dsl/inside_route.rb, spec/grape/dsl/inside_route_spec.rb
This is a very simple implementation of feature requested in #934.
=> Allow symbols for status codes

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/dsl/inside_route_spec.rb
- Raise error if given status code is not included Rack::HTTP_STATUS_CODES
- Raise error if given status is not a Fixnum or Symbol
=> Raise error if unknow status code is passed to #status

lib/grape/dsl/inside_route.rb, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb
This is a fixup for #952
I didn't edit changelog because #952 change description still seems valid.
=> Allow all Fixnum statuses

lib/grape/dsl/routing.rb, spec/grape/dsl/routing_spec.rb
Add pending specs for Routing module. Merging this PR will close #874.
Added specs for following methods:
- group
- resource
- resources
- segment
- namespace
- routes
- route_param
- route
=> Add routing specs

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/presenters/presenter.rb, spec/grape/presenters/presenter_spec.rb
=> Support present hash

.travis.yml
Support for Ruby 1.9.3 is officially over and security patches will not be backdated. It might be worth removing it from the travis build matrix.
https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/
=> Remove Ruby 1.9.3 from travis.

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/error_formatter/json.rb, lib/grape/exceptions/validation_errors.rb, lib/grape/middleware/error.rb, spec/grape/exceptions/validation_errors_spec.rb
I was having a similar problem with `ValidationErrors#to_json` as I was with `ValidationErrors#as_json` (see: #889). If there's preferred fix, please let me know.
=> error! in rescue from blocks

spec/grape/dsl/parameters_spec.rb
```
Grape::DSL::Parameters
#use
An expectation of :namespace_stackable was set on nil. Called from /Users/u2/grape/spec/grape/dsl/parameters_spec.rb:49:in `block (3 levels) in <module:DSL>'. Use allow_message_expectations_on_nil to disable warnings.
calls processes associated with named params
An expectation of :namespace_stackable was set on nil. Called from /Users/u2/grape/spec/grape/dsl/parameters_spec.rb:49:in `block (3 levels) in <module:DSL>'. Use allow_message_expectations_on_nil to disable warnings.
raises error when non-existent named param is called
```
=> Use allow_message_expectations_on_nil to disable warnings

CHANGELOG.md, lib/grape.rb
http://blog.plataformatec.com.br/2012/08/eager-loading-for-greater-good/
Eager loading may be greater good.
=> Add eager loading

.rubocop_todo.yml, CHANGELOG.md, lib/grape/dsl/routing.rb, lib/grape/endpoint.rb, spec/grape/dsl/routing_spec.rb
=> Fixed duplicating endpoints

README.md
Adding request logging with parameters, error codes etc was always the first thing after starting new grape project for me so I though I would make a gem out of it and make it easier for the other developers.   Putting it in the readme would help spread the word!
[grape_logging](https://github.com/aserafin/grape_logging)
=> mention grape_logging in documentation

CHANGELOG.md, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
> I like Virtus's support for coercion to Sets as seen here:
https://github.com/solnic/virtus#collection-member-coercions
> They can be treated the same as Arrays in the case of `nil`, and changing line 41 from `@option[0]` to `@option.first` behaves the same for either.
=> Added support for coercion to Set or Set[Other]

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/path.rb, spec/grape/api/deeply_included_options_spec.rb, spec/grape/api_spec.rb, spec/grape/path_spec.rb
Hi,
so I had an issue #965 After investigating it all, it seemed like it was very unexpected behavior:
```
format :json
get '/users' => { status: 200, content_type: 'application/json' }
get '/users.json' => { status: 404 }
```
introduced with PR #809 
It turned out it was strictly related to the issue I was having. I think it's logical to allow calling endpoint with specified format.
I saw @dblock comments about changing this ([1](https://github.com/intridea/grape/pull/809#issuecomment-71589211), [2](https://github.com/intridea/grape/issues/914#issuecomment-78918521)) so I decided to do this.
I've also added specs with the specific issue I was having with deeply nesting concerns.
Best
=> Use proper .format suffix if you have one path, issue 965

CHANGELOG.md, lib/grape.rb, lib/grape/middleware/globals.rb, spec/grape/middleware/globals_spec.rb
- add to the autoload configuration
- fix issues with it accessing an undefined var/method
This is a fix for #1003
=> fix the Globals middleware

README.md
Fixed order of the arguments of assert_equal that was supposed to reverse.
=> Fix assert_equal arguments order in README

CHANGELOG.md, lib/grape/validations/validators/allow_blank.rb, spec/grape/validations/validators/allow_blank_spec.rb
Fix allow_blank validator such that validation will not fail when a value of false is sent in a boolean param and allow_blank is set to false.
=> allow_blank boolean fix

.travis.yml
I believe grape will support ruby-2.2 so I added that in travis. if not please close the pull request.
=> Updated ruby version

CHANGELOG.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, spec/grape/dsl/inside_route_spec.rb
Fixes https://github.com/intridea/grape/issues/1023.
=> Only merge representations onto an existing body.

CHANGELOG.md, lib/grape/validations/validators/multiple_params_base.rb, spec/grape/validations_spec.rb
This fixes an issue with `mutual_exclusive` params inside a `type: Hash` param.
With these params:
```ruby
params do
optional :wine, type: Hash do
optional :grape
optional :country
mutually_exclusive :grape, :country
end
end
```
And the request params `{ wine: "This is a string, not a hash" }`
I'd expect an error message, but instead get an unhandled error:
undefined method `stringify_keys' for "This is a string, not a hash":String
=> Fixed validation of invalid params with mutual_exclusive inside hash

lib/grape/middleware/formatter.rb, spec/grape/middleware/formatter_spec.rb
Related to https://github.com/intridea/grape/pull/1026
=> Do not convert a Rack::Response to an array.

lib/grape/util/stackable_values.rb, spec/grape/util/stackable_values_spec.rb
To fix #930, settings managed with `StackableValues` (including custom middleware) are now `dup`ed instead of `deep_dup`ed when `mount` is used.
Although it's a small change in terms of character count, the impact seems large. One category of affected code appears to be "custom middleware that maintains global state" like [Warden's test hook system](https://github.com/hassox/warden/blob/master/lib/warden/test/warden_helpers.rb), but there may be many others.
Please note that to reduce the impact, _only_ `StackableValues` has been modified. `InheritableValues`, which also persists settings, still uses `deep_dup`.  If this inconsistency is confusing or otherwise undesirable, I'm happy to drop `deep_dup` usage (and support) entirely. Regardless, I'm hoping the authors of #739 can weigh in …
=> Only dup StackableValues

CHANGELOG.md, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
=> Fix coercion of complex arrays

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/util/parameter_types.rb, lib/grape/validations/validators/coerce.rb, spec/grape/util/parameter_types_spec.rb, spec/grape/validations/params_scope_spec.rb
This implements #993. Originally, I thought it'd be possible to do this simply by having the custom type extend Virtus::Attribute, but a) it turned out to not be that easy and b) I figured it'd be better to define a pattern for this that isn't directly coupled to Virtus.
So, my change allows you to take any class and coerce parameters into it. All that's required is that the class implement a `from_param` class method. This name is arbitrary, but I feel it matches up with the intent of the change... totally open to suggestions, though. As a quick example:
```ruby
class Color
attr_reader :value
def initialize(color)
@value = color
end
def self.from_param(value)
raise "Invalid color" unless %w(blue red green).include?(value)
new(value)
end
end
params do
required :color, type: Color, …
```
=> Support custom types

lib/grape/api.rb, lib/grape/dsl/callbacks.rb, lib/grape/dsl/configuration.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/parameters.rb, lib/grape/dsl/routing.rb, lib/grape/dsl/settings.rb, lib/grape/dsl/validations.rb, lib/grape/namespace.rb, lib/grape/path.rb, lib/grape/route.rb, lib/grape/util/inheritable_setting.rb, lib/grape/util/parameter_types.rb, lib/grape/validations.rb, lib/grape/validations/params_scope.rb, lib/grape/version.rb
It's pretty mundane, but this PR increases docs coverage from ~37% to ~50% and fixes the YARD warnings currently in `master`. There's a lot more to do, but this is a start. I did my best to make the documentation moderately useful (as opposed to just restating the method name), but I'd appreciate review of my longer comments in case I've misrepresented anything!
Before:
```
$ yard
[warn]: @param tag has unknown parameter name: name
in file `lib/grape/api.rb' near line 39
[warn]: Unknown tag @returns in file `lib/grape/util/parameter_types.rb` near line 34
[warn]: Unknown tag @returns in file `lib/grape/util/parameter_types.rb` near line 43
[warn]: Unknown tag @returns in file `lib/grape/util/parameter_types.rb` near line 51
Files:          88
Modules:        54 (   52 undocumented) …
```
=> Increase documentation coverage

CHANGELOG.md, lib/grape/middleware/base.rb, spec/grape/middleware/base_spec.rb
While using https://github.com/aserafin/grape_logging grape middleware after an upgrading grape from 0.11 to 0.12 I've been stuck with an issue (https://github.com/aserafin/grape_logging/issues/6):
```
NoMethodError (undefined method `downcase' for 2:Fixnum)
```
That's because `Middleware#response` tries to convert `Rack::Response` to `Rack::Response` and fails.
=> Do not convert Rack::Response to Rack::Response

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/dsl/parameters.rb, lib/grape/exceptions/unknown_parameter.rb, lib/grape/locale/en.yml, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
Implements #958 (sort of). This allows for the use case where you have some parameters to an endpoint which are only relevant or meaningful if some other parameters are given. It can be used like so:
```ruby
params do
optional :shelf_id, type: Integer
given :shelf_id do
requires :bin_id, type: Integer
end
end
```
Nested use cases work, too:
```ruby
params do
requires :product_info, type: Hash do
requires :name, type: String
optional :shelf_id, type: Integer
given :shelf_id do
requires :bin_id, type: Integer
end
end
```
One concern: This type of relationship won't show up properly in grape-swagger, or anything which looks at `Route#route_params` to inspect parameter definitions; even though the elements in the `given` block are actually optional unless `shelf_id` is given, …
=> Validate params only if another param is present

grape.gemspec
Rubyforge.org [closed](https://twitter.com/evanphx/status/399552820380053505) on May 15, 2014, and rubyforge_project attribute [became deprecated](http://rubygems.rubyforge.org/rubygems-update/Gem/Specification.html#attribute-i-rubyforge_project). Remove it from gemspec, then.
=> Remove deprecated rubyforge_project attribute from gemspec

README.md
This PR adds a line to the README that lets people know about the grape-route-helpers gem. I'll add it to the wiki like @dblock suggested, too.
=> Add a link to grape-route-helpers gem in the README

lib/grape/http/headers.rb, lib/grape/middleware/formatter.rb, spec/grape/middleware/formatter_spec.rb
Hello!
What was the purpose of finding a `HtTp_AccEPT` case-insensitive way? It also requires traversing all the giant `env` hash :sob:  I cannot find any good reason for doing this and think it's a sort of obsolete stuff.
https://tools.ietf.org/html/rfc3875 says that all the `HTTP_` things are uppercased.
Even if there's a good reason for doing this we should anyway decide what to do with the fact that Grape accesses `Accept` header from another middleware [`Grape::Middleware::Versioner::Header`](https://github.com/intridea/grape/blob/e0b73571388780d46f20cd1fa6bdbb70e5a9b74f/lib/grape/middleware/versioner/header.rb#L87) using uppercased `'HTTP_ACCEPT'`.
=> Remove case insensitive Accept header support

CHANGELOG.md, README.md, lib/grape/exceptions/validation_errors.rb, spec/grape/exceptions/validation_errors_spec.rb
Belongs to https://github.com/intridea/grape/issues/1058. 
A `Grape::Exceptions::ValidationErrors` responds now public to #full_messages and returns an array of of the validation messages.
=> Make Grape::Exceptions::ValidationErrors#full_messages public

CHANGELOG.md, lib/grape/endpoint.rb, lib/grape/exceptions/validation_errors.rb, spec/grape/endpoint_spec.rb, spec/grape/exceptions/validation_errors_spec.rb
Adding headers to validation errors instance to be used in error response.
#1062
=> Adding headers to validation errors

lib/grape/dsl/settings.rb
In /lib/grape/dsl/settings.rb there was a call to `reset_validations!` that seemed necessary. All the tests are passing.
=> No longer resetting validations twice

.rubocop_todo.yml, CHANGELOG.md, README.md, lib/grape.rb, lib/grape/dsl/inside_route.rb, lib/grape/middleware/formatter.rb, lib/grape/util/file_response.rb, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb
Also necessary was the introduction of an object (`FileResponse`) so the formatting middleware would leave files and other enumerables alone. Seemed better than relying on methods on the object as enumerables have `each` defined. I've been writing scala recently so I think I have case classes on the brain.
=> Add `stream` method to InsideRoute to leverage Rack::Chunked

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/validators/values_spec.rb
This PR fixes https://github.com/ruby-grape/grape/issues/1091, also tested with an example grape app to reproduce the bug (see https://github.com/towanda/grape-boolean-example/blob/master/example.rb)
=> Fix boolean type

CHANGELOG.md, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
This one fixes a serious problem we faced in production under a heavy load. Investigation led us to the fact that it happens only when params are defined with `type: Array[SomeClass]`. In this case `Virtus` dynamically create some virtual classes (with `Class.new`) which inherits from base class with `DescendantsTracker` added which saves descendant classes into the array. Here we have a leak because garbage collector doesn't free these classes because an array still holds a reference to them.
So at least I can say that `Virtus` isn't designed for creating things *dynamically*. They should be stored somehow statically.
@dblock 
Look, this is funny! Remember https://github.com/ruby-grape/grape-entity/pull/161 ? This is why it is bad to store descendant classes in the array. Look at the …
=> Memoize Virtus attribute and fix memory leak.

CHANGELOG.md, lib/grape/dsl/configuration.rb, spec/grape/dsl/configuration_spec.rb
Raise a warning when `desc` is called with options hash and block.
relates to: #920
=> Raise a warning when `desc` is called with options hash and block 

lib/grape/dsl/parameters.rb, lib/grape/dsl/request_response.rb, lib/grape/dsl/routing.rb
This one, on the contrary to #1122, #1124, utilizes ActiveSupport feature.
`extract_options!` is harmless and not heavy, also `Grape` already uses it in some place.
It should not impact performance since the fixed methods  are `DSL` methods (they're called just once). Here we better have clarity.
=> Use extract_options!

lib/grape/dsl/inside_route.rb
=> Use constant RACK_ROUTING_ARGS instead of string.

lib/grape/dsl/inside_route.rb, lib/grape/formatter/serializable_hash.rb
`each_with_object` sometimes is better than `inject`.
=> Use each_with_object instead of inject.

README.md
We released built-in support for Grape instrumentation a few months ago and realized we should probably update the list here as well!
=> Add built-in New Relic support to Monitoring options

CHANGELOG.md, README.md, UPGRADING.md, lib/grape.rb, lib/grape/exceptions/invalid_version_header.rb, lib/grape/locale/en.yml, lib/grape/middleware/error.rb, lib/grape/middleware/versioner/header.rb, spec/grape/exceptions/invalid_accept_header_spec.rb, spec/grape/middleware/versioner/header_spec.rb
A suggested fix for https://github.com/ruby-grape/grape/issues/968
There are two failing specs which show that unfortunately there is no way to `rescue_from` an invalid version, since it's possibly valid and needs to propogate. This was also the case before the regression was introduced.
=> Fix rescue all header versioning regression

.rubocop_todo.yml, CHANGELOG.md, README.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, lib/grape/endpoint.rb, spec/grape/dsl/inside_route_spec.rb, spec/grape/endpoint_spec.rb
In response to issue #1074
This adds a mechanism by which Grape::DSL::InsideRoute methods may be
overriden after certain filters are run.
The first problem case of a filter being utilized before it should that
necessitated this enhancement is the `#declared` method, which was
returning un-coerced params in `before` filters.
There may be other problem cases, which may be rectified using this same
mechanism.
=> Makes #declared unavailable to before filters

CHANGELOG.md, lib/grape/dsl/helpers.rb, spec/grape/dsl/helpers_spec.rb
See https://github.com/ruby-grape/grape/issues/1144.
=> Fixes boolean declaration in an external helper file.

CHANGELOG.md, lib/grape/validations/validators/values.rb, spec/grape/validations_spec.rb
This fixes an edge case where the API would blow up with a `"no implicit conversion of Symbol into Integer"`.
To trigger the error, make a param nested inside a `Hash` param and add `values` validations to the param. Then send something that is not a hash to the outer param. (see spec)
=> Fixed edge case regarding Hash with inner param

spec/spec_helper.rb
This should close https://github.com/ruby-grape/grape/issues/1155.
=> Removes double require in spec_helper.

CHANGELOG.md, README.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
Addresses issue #1135. Adds `coerce_using` option to
`Grape::DSL::Parameters::requires` and `::optional`,
allowing implementors arbitrary coercion uncoupled
from the parameter type.
See README.md#custom-types-and-coercions for usage.
=> Custom parameter coercion using `coerce_with` #1135

CHANGELOG.md, README.md, lib/grape/dsl/parameters.rb, lib/grape/locale/en.yml, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
Addresses issue #1135. Allows `type: JSON` and `type: Array[JSON]`
as options for `Grape::DSL::Parameters::requires` and `::optional`,
allowing convenient handling of parameters supplied as JSON-encoded
strings.
See README.md#first-class-json-types for usage.
=> First-class JSON parameter type #1135

lib/grape/dsl/configuration.rb, lib/grape/util/content_types.rb
If we are calling ```.blank?```, calling ```.nil?``` first is redundant.
=> Removes redundant nil? check.

CHANGELOG.md, README.md, lib/grape/middleware/versioner/header.rb, spec/grape/middleware/versioner/header_spec.rb
The current accept header parsing logic treats everything after the first `-` as the version, whereas it's not uncommon to have dashes in more complex vendor/resource media type definitions (an IANA-registered example is `application/vnd.ms-office.activeX+xml`)
This change correctly handles dashes in the vendor part, while still assuming what's after the last dash is the version.
The current logic also doesn't allow underscores, ampersands, etc, which are allowed media type characters per [RFC 6838](http://tools.ietf.org/html/rfc6838#section-4.2). This change makes Grape itself handle these characters correctly, however for them to actually work is contingent on https://github.com/mjackson/rack-accept/pull/17 which unfortunately has been open for more than 6 months (I'll ping maintainer …
=> allow dashes, periods, and other RFC6838-compliant characters in header vendor

README.md
Should we change the example to this as `[foo: :bar]` will actually return an array that contains a hash?
=> Update describing method headers example

CHANGELOG.md, lib/grape/middleware/formatter.rb, spec/grape/middleware/formatter_spec.rb
When using custom vendored content types the specified formatters were not being used because only the generalized type was being made available to match.
`Grape::Middleware::Formatter#mime_array` - when provided with accept header `application/vnd.mycompany.upcase+txt` - has previously returned 
``` ruby
[ 'application/txt']
```
and now returns 
``` ruby
['application/vnd.mycompany.upcase+txt',  'application/txt']
``` 
This allows `Grape::Middleware::Formatter#format_from_header` to match the custom type and proceed to use the custom formatter.
```ruby
class Hello < Grape::API
content_type :upcase, 'application/vnd.mycompany.upcase+txt'
formatter :upcase, ->(obj, env){ obj.upcase }
content_type :dashed, 'application/vnd.mycompany.dashed+txt'
formatter :dashed, ->(obj, env){ obj.tr(' ', …
```
=> Use formatters for custom vendored content types.

CHANGELOG.md, README.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/types.rb, lib/grape/validations/types/build_coercer.rb, lib/grape/validations/types/multiple_type_coercer.rb, lib/grape/validations/types/variant_collection_coercer.rb, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
Fixes #693.
Adds `types` option for `requires` and `optional` endpoint parameter
declarations, allowing for parameters that have more than one allowed
type. See README.md for usage.
I have been thinking about the best way to expose some of the more
interesting possibilities for arbitrary type validation that are hidden in Grape,
but in the end this is the only use case I have seen that makes sense to me.
=> Allow parameters with more than one type.

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/middleware/formatter.rb, spec/grape/api_spec.rb, spec/grape/middleware/formatter_spec.rb
Allow the formatter middleware to bypass serialization of response bodies when the status indicates there is no content.
#1162 describes a scenario where `OPTIONS` requests and redirects can raise exceptions when content types are limited to those that don't consider `''` as valid or are not prepared to handle it.  The specific example given involved content types being limited (or set by default) to XML. `''` is not consider to be valid XML and as such results in an error when serialization is attempted. 
A resolution was proposed to handle this in the formatters by checking the request method.  It seems - and was suggested - that this opens up the scope of concern for the formatters too much and I agree. Additionally, it places a burden on all custom formatters to account for responses …
=> Bypass formatting for statuses with no entity-body

README.md
1. In ruby, regexp default mode is multiline mode.
2. [[:alnum:]] don't match only ascii character. it match also multibyte character.
for example.
about 1.
```ruby
$ irb
2.2.1 :001 > "aaaa\nbbbb\nccc" =~ /^b+$/
=> 5
2.2.1 :002 > "aaaa\nbbbb\nccc" =~ /\Ab+\z/
=> nil
```
about 2.
```ruby
$ irb
2.2.1 :001 > "あ" =~ /\A[[:alnum:]]+\z/
=> 0
2.2.1 :002 > "A" =~ /\A[[:alnum:]]+\z/
=> 0
```
I think that it may become vulnerability.
so, it is better to quit as a sample.
=> Fixed regexp that match unintended string in README.md.

CHANGELOG.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
This change forces redirect to use a content type of `text/plain` to both bypass any serialization attempts by the formatters and more closely meet the spec defined for [redirection](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3).
Original issue #1157.  Related issues #1162, #1159
The original issue here was concerned with the XML formatter attempting to serialize an empty body when an redirect was invoked. The situation can happen when an API is limited to XML only, or when XML is supported and requested.
[The HTTP spec for redirection](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) states:
> Unless the request method was HEAD, the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s).
I interpret this as …
=> Redirect as plain text with message.

.rubocop_todo.yml, lib/grape/endpoint.rb
Hello!
This is an attempt to fix a most wrong thing in Grape: middleware stack is initializing *on every request* and even more Grape `dup` them when they're called.
I don't know should it be merged or not. It might break someone's code even when specs are green.
=> Don't call builder on every request.

benchmark/simple.rb, grape.gemspec, lib/grape/formatter/serializable_hash.rb, lib/grape/middleware/base.rb, lib/grape/request.rb, lib/grape/util/strict_hash_configuration.rb
Remove `each_with_object` where it's slow.
Remember https://github.com/ruby-grape/grape/pull/1128?
Unfortunately, calling `each_with_object` on `Hash` is not a good idea (`inject` has the same problem btw). It allocates an array for each `(k,v)` pair which is not good.
More details here: https://github.com/rails/rails/commit/960de47f0eef79d234eb3cfc47fabb470fef1529
@tenderlove exellently covered it all.
=> Ditch each_with_object

.rubocop_todo.yml, lib/grape/dsl/inside_route.rb, lib/grape/endpoint.rb, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb
Now I'm working on reducing calls to `extend` in `Grape` because they invalidate Ruby's method cache slowing everything down. I applied a *clever* trick with subclassing `Endpoint` and including helpers into this subclass.
It also forced me to fix a thread safety issue reported by @etehtsea here: https://github.com/ruby-grape/grape/pull/1201#discussion_r44900471 because calling `include` twice would be really inconsistent.
Also I'm sorry, 06930da does not actually fix anything, I overlooked it :)
=> Lazy initialization of Endpoint and trick with helpers.

grape.gemspec
=> Removing dependence on git in gemspec

CHANGELOG.md, lib/grape/validations/attributes_iterator.rb, lib/grape/validations/params_scope.rb, spec/grape/validations/validators/coerce_spec.rb, spec/grape/validations_spec.rb
This PR implements https://github.com/ruby-grape/grape/issues/1131
=> Provides Array index context in errors.

spec/grape/api_spec.rb
The build broke, but I cannot figure out exactly why, the only difference is the version of grape-entity brought in.
=> Fix standard logger format.

spec/grape/middleware/versioner/header_spec.rb
As discussed on #1206 it was fixed on #1101 but there was not spec for multiple accept headers.
=> Add spec for strict request with multiple accept headers

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
When a lateral scope is defined push the declared params on the parent and not itself,
Fixes #1219 
I added extra test case. Another issue is still not fixed, described in the following spec:
```ruby
it 'includes level 2 nested parameter within #declared(params)' do
subject.params do
requires :bar, type: Hash do
optional :a
optional :c, type: Hash do
given :a do
requires :b
end
end
end
end
subject.get('/nested') { declared(params).to_json }
get '/nested', bar: { a: true, c: { b: 'yes' } }
expect(JSON.parse(last_response.body)).to eq('bar' => { 'a' => "true", 'b' => 'yes' })
end
```
For this the validation of the given DSL should be moved somewhere else. Right now `given` only works for parameters defined in the same block. I highly doubt that somebody would need this level of complexity …
=> Fix Given with nested params

spec/grape/api_spec.rb, spec/grape/middleware/exception_spec.rb, spec/grape/middleware/formatter_spec.rb, spec/grape/validations_spec.rb
Fix hash duplicated keys and raise_error specs avoiding warnings during the build.
=> Fix build warnings

.travis.yml, gemfiles/rails_3.gemfile
=> Use Ruby 2.3.0 on Travis

README.md, spec/grape/api_spec.rb, spec/spec_helper.rb
I guess we can use `CGI.escape` instead of `URI.escape`.
Ref: https://github.com/ruby/ruby/commit/238b979f1789f95262a267d8df6239806f2859cc
=> Don't use URI.escape as it has been obsoluted

CHANGELOG.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
It will now expect any amount of inputs and will iterate on the input
=> Changed the input of `given`

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/middleware/base.rb, lib/grape/middleware/formatter.rb, spec/grape/middleware/base_spec.rb
This might be able to close #1147.
Could you review this PR?
=> Call #after of middleware on error

CHANGELOG.md, lib/grape/validations/validators/default.rb, spec/grape/validations/validators/default_spec.rb
=> Don't fail even if invalid type value is provided

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
I believe the following two params blocks should be valid:
~~~
params { optional :numbers, type: Array[Integer], values: 0..2, default: 0..2 }
~~~
~~~
subject.params { optional :numbers, type: Array[Integer], values: [0, 1, 2], default: [1, 0] }
~~~
The current implementation doesn't account for these use cases and raises `Grape::Exceptions::IncompatibleOptionValues`.  This PR will allow the two cases above.
=> do not raise an IncompatibleOptionValues For a couple of potentially valid use cases

README.md
I think we should not use hash rocket unless there is any particular reason.
=> Don't use hash rocket unless there is any particular reason [ci skip]

CHANGELOG.md, README.md, lib/grape/dsl/routing.rb, spec/grape/api_spec.rb
ref #1009 
I'd like to use type definition in `route_param`, so I implemented it by using `requires` DSL.
=> Allow param type definition in route_param

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
I believe this may be a fix for the intention of #1119, or maybe just its own small bug
=> Fix Allow header including OPTIONS when do_not_route_options! set

README.md, spec/grape/endpoint_spec.rb
References #1251, #1253 
I found that there is already support for using `present` in a `before` filter. Any filter actually, along with `error!`. Using `error!` will act as though the response stops there completely. Any filter or api call that would have happened afterwords is not called (including `after` to be specific to #1253).
Wrote specs and documentation for current behavior
=> Adds documentation and specs for callback response behaviors

CHANGELOG.md, lib/grape/middleware/versioner/param.rb, spec/grape/middleware/versioner/param_spec.rb
Issue: https://github.com/ruby-grape/grape/issues/1270
Currently, we're looking for the parameter in ```@options``` instead of ```@options[:version_options]```. This should fix the issue.
=> Param versioning will now correctly set parameter key

CHANGELOG.md, lib/grape.rb, lib/grape/api.rb, lib/grape/exceptions/method_not_allowed.rb, spec/grape/api_spec.rb
Problem:
All requests to Not Allowed methods are returning 500 error instead of
405 when the format is xml.
Cause:
Route definitions for not allowed methods are returning an empty string
as a response body. But the empty string fails to convert to xml and
raises InvalidFormatter error.
Solution:
Define an exception for "method is not allowed" case.
Return an error message "405 Not Allowed" instead of empty string.
=> Fix 500 error for xml format when method is not allowed

CHANGELOG.md, lib/grape/middleware/base.rb, spec/grape/middleware/base_spec.rb
https://github.com/ruby-grape/grape/issues/1265
See discussion in the issue...
=> After callback warning

spec/grape/api_spec.rb
=> Don't include extension in capture if format is specified

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/middleware/formatter.rb, lib/grape/util/sendfile_response.rb, spec/grape/integration/rack_sendfile_spec.rb, spec/grape/middleware/formatter_spec.rb
Hello.
I've added support of `Rack::Sendfile` middleware. Before this fix` Rack::Sendfile` does not apply strategy of adding X-Accel-Redirect (or X-Sendfile) header, because Grape returns simple `Rack::Response` which doesn't respond to `to_path` method. So I've implemented simple `SendfileReponse` class which responds to `to_path`.
=> Support Rack::Sendfile middleware

README.md, spec/grape/api/custom_validations_spec.rb
Wanted to be able to have custom validation based on request and parameter. As an example wanted to be able to have _Admin Only_ fields that are only available to endpoint if user is admin.
With new `validate(request)` method added for custom validation (https://github.com/ruby-grape/grape/pull/1242) we can now support these kinds of attributes. I only added a new sample in spec and also a sample in README.md.
=> Added a sample spec and example in README.md for admin only fields

spec/grape/api_spec.rb
ref #1057
I've cherry-picked @ekampp's commit and fixed a little bit.
Thoughts?
=> Add test for OPTIONS and HEAD requests with catch-all

CHANGELOG.md, README.md, lib/grape/validations/types/custom_type_coercer.rb, spec/grape/validations/validators/coerce_spec.rb
Fixes #1324, Allow using ```coerce_with``` when type is either ```Array[String]``` or ```Array[Integer]```
=> Params: Fix coerce_with helper and Arrays types

CHANGELOG.md, lib/grape/error_formatter.rb, lib/grape/formatter.rb, lib/grape/parser.rb, lib/grape/util/registrable.rb, spec/grape/middleware/formatter_spec.rb
ref 93e699829f7b4a2fe152370eccdf9b2712f4329f #1329 
I'd like to use grape-msgpack without tricky hacking. Currently, our implementation does not support inheritable interface, so I fixed a few points.
Thoughts?
=> Fix built-in parsers and formatters

CHANGELOG.md, lib/grape/error_formatter/base.rb, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb
This change allows an immutable hash, for example a frozen constant, to be passed as the message to `error!`.
If a `:with` value needs to removed from the specified message then a new hash is created without that key.
=> Do not modify a Hash argument to error!

CHANGELOG.md, README.md, lib/grape/api.rb, lib/grape/router.rb, spec/grape/api/recognize_path_spec.rb, spec/grape/dsl/inside_route_spec.rb
ref #1072 
I've tried to implement `Grape::DSL::InsideRoute#recognize_path`.
It returns value conforming the format like `[original pattern, expanded params]`.
This is a first step. I'd like to hear your opinions.
Thanks.
=> Implement Grape::API.recognize_path

grape.gemspec
=> Workaround for #1350, lock grape-entity at 0.5.0.

CHANGELOG.md, lib/grape/router/attribute_translator.rb, lib/grape/router/route.rb, spec/grape/integration/global_namespace_function_spec.rb
Fixes https://github.com/ruby-grape/grape/issues/1348.
A globally defined `def namespace` in Ruby 2.3.0 pollutes OStruct instance methods. This is described in https://bugs.ruby-lang.org/issues/12136 and https://bugs.ruby-lang.org/issues/12251. One way to reproduce this is to `include Rake::DSL` in the global scope, which defines a global `namespace` method.
This PR gets rid of the OStruct. We cannot use a `Hash` here because we want to respond to methods like `.index` which are natively defined on a `Hash`, so we need a dummy structure that responds to anything. Because it behaves like a Hash though we don't need to register parameters or such, cc: @namusyaka in case I missed anything.
=> Fix #1348: global functions called during mount.

CHANGELOG.md, README.md, lib/grape/router/route.rb, spec/grape/api_spec.rb
=> Fix incorrect deprecations

CHANGELOG.md, lib/grape/router.rb, spec/grape/integration/version_header_spec.rb
ref #1355 #1356 
The `PATCH` bug is caused by calling `Grape::Middleware::Versioner::Header`.
Now, grape router calls it because you can not eject route except first route of all routes having same paths.
But maybe it has no problem essentially.
So I think this problem can be solved by not call the middleware.
/cc @dblock
=> Fix router bugs

CHANGELOG.md, lib/grape/exceptions/validation.rb, spec/grape/exceptions/validation_spec.rb
In my situation, in the exception validations, I need message keys as well as the translations in order to pass error codes
=> add back message key in order to have error_codes

lib/grape/util/stackable_values.rb
I profiled our app that uses Grape and looks like the StackableValues#[name] ([this code](https://github.com/ruby-grape/grape/blob/master/lib/grape/util/stackable_values.rb#L14-L20)) takes most of the time. And it's good idea to improve its performance. So I tried to do this.
It gives some performance. Here my benchmarks:
```ruby
Benchmark.ips do |x|
x.report(:old) do
value = [@inherited_values[name], @new_values[name]]
value.compact!
value.flatten!(1)
value
end
x.report(:new) do
value = []
value.concat(@inherited_values[name]) if @inherited_values[name]
value.concat(@new_values[name]) if @new_values[name]
value
end
end
```
And the results:
```
Warming up --------------------------------------
old    61.139k i/100ms
new   173.740k i/100ms
Calculating ------------------------------------- …
```
=> Improve performance for StackableValues#[name] method

CHANGELOG.md, README.md, lib/grape/dsl/middleware.rb, lib/grape/endpoint.rb, lib/grape/middleware/stack.rb, lib/grape/util/stackable_values.rb, spec/grape/api_spec.rb, spec/grape/dsl/middleware_spec.rb, spec/grape/middleware/stack_spec.rb
This pull request is inspired by #794. I was using Grape and found myself needing this feature, so I have built a possible way of supporting `insert`, `insert_after` and `insert_before` in a similar way as Rails does.
Adding a new middleware can now be done through `use`, `insert`, `insert_after` and `insert_before`, and the operation chosen to do so is stacked together with the middleware class, args, and blocks. The stack is built using the operations in `Grape::Endpoint#build_stack` using a new class `Grape::Middleware::Stack`, based on `ActionDispatch::MiddlewareStack` with some simplifications (for example, only classes are supported for middleware, no symbols or strings, which is being deprecated in `ActionDispatch` in any case).
The commit message offers more details on the …
=> Allow inserting middleware at arbitrary points in the middleware stack

CHANGELOG.md, lib/grape/endpoint.rb, lib/grape/middleware/stack.rb, spec/grape/middleware/stack_spec.rb
Builds onto the new middleware stack introduced in https://github.com/ruby-grape/grape/pull/1390. This is useful because it allows positioning of middleware around default Grape middleware.
=> Middleware can be inserted before or after defaults

README.md
As for me, with current version of Readme it isn't obvious that you could combine `rescue_from :all` and `rescue_from CustomError`. But at the moment it's probably the only way to properly handle validation errors and giving fallback for other exceptions. I am not alone with this issue: @johnsinco has created #938 and part of the source for this PR was kindly provided by @dblock in #939.
By the way, what do you think about having something like this?
```ruby
rescue_from :all, except: [Grape::Exceptions::Validation, Grape::Exceptions::ValidationErrors]
rescue_from :all, except: :validation_errors
```
Maybe this approach would be useful to utilize both default way to handle validation errors and all other errors (without need to manually handle them).
=> clarify possibility to combine rescuing all and custom exceptions

CHANGELOG.md, README.md, UPGRADING.md, lib/grape.rb, lib/grape/dsl/request_response.rb, lib/grape/dsl/settings.rb, lib/grape/endpoint.rb, lib/grape/middleware/error.rb, lib/grape/util/inheritable_setting.rb, lib/grape/util/reverse_stackable_values.rb, spec/grape/api_spec.rb, spec/grape/dsl/request_response_spec.rb, spec/grape/util/inheritable_setting_spec.rb, spec/grape/util/reverse_stackable_values_spec.rb
I'm starting to work on errors handling improvements. First of all, I've introduced a failing spec: from my point of view, rescuing specific error should take precedence over rescuing its base, but it doesn't. 
@dblock, could you please explain to me, if it's a bug or a feature? Should I keep this behavior during my changes?
=> Exceptions aren't rescued in a predictable order

CHANGELOG.md, lib/grape/dsl/routing.rb, spec/grape/api_spec.rb
It is a fix for issue #1400
I created a new spec for this case and found out why it was not working.
=> Fix multiple version definitions for path versioning

README.md
This is related to issue #1413 
It's not clear by reading the docs that when using the `Accept-Version header` a `406` will only be returned IF `:cascade` is set to `false`.This PR aims to make that behavior more visible in the docs.
=> Improve docs related to the `Accept-Version Header`

CHANGELOG.md, lib/grape/endpoint.rb, lib/grape/middleware/error.rb, spec/grape/api_spec.rb
ref #1420 
/cc @etehtsea @dblock
=> Avoid polluting Grape::Middleware::Error

CHANGELOG.md, lib/grape/api.rb, lib/grape/endpoint.rb, spec/grape/endpoint_spec.rb
ref #1085 
I cherry-picked changes from @plukevdh and @rnubel commits, and fixed a few points.
The issue should be fixed in this pull request.
@dblock Could you review this?
/cc @plukevdh @rnubel
=> Concatenate parent declared params with current one

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/endpoint_spec.rb
I check some specs on my project and I find out that this functionality work little bit wrong with declared when we have several route_param in one namespace.
For example we have:
```ruby
class Artists
namespace :artists do
route_param :id, type: Integer do
get do
declared(params)
end
params do
requires :filter, type: String
end
get :some_route do
declared(params)
end
end
route_param :artist_id, type: Integer do
mount Compositions
end
end
end
```
`declared(params)` should return us next hash `{id: 1}`, but it return hash `{id: 1, artist_id: nil}`.
Also in first `route_param` in second endpoint(`get :some_route`) when we call `declared(params)` we have only `filter` params in returned hash `{filter: 'some_filter'}`
P.S.: I find out where we have problem! Problem is in options for …
=> specs for declared(params) inside route_param bug.

CHANGELOG.md, README.md, lib/grape/dsl/request_response.rb, lib/grape/endpoint.rb, lib/grape/middleware/error.rb, spec/grape/dsl/request_response_spec.rb, spec/grape/exceptions/body_parse_errors_spec.rb
This will allow Grape to use the built in Grape Exceptions defined in /lib/grape/exceptions when rescue :all is set.
=> adding option to allow grape to handle Grape::Exception when rescue all is set

CHANGELOG.md, README.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
=> Extended given to receive a Proc

.rubocop.yml, .travis.yml, CHANGELOG.md, Dangerfile, Gemfile, gemfiles/rack_1.5.2.gemfile, gemfiles/rails_3.gemfile, gemfiles/rails_4.gemfile, lib/grape.rb
Sorry ~250 watchers, I got hit by https://github.com/isaacs/github/issues/361
**Pre-requisite**
This requires the CI ENV var `DANGER_GITHUB_API_TOKEN` to be set up, so someone has to [follow this guide](http://danger.systems/guides/getting_started.html) from "Creating a GitHub Account for Danger to use". 
I'd recommend making a new GitHub account for GrapeCI - see our [DangerCI one](https://github.com/DangerCI?tab=activity), don't give it access to any of the repos. 
Then re-build this PR. I've not made any README changes, so it should show a message about me adding one.
=> Add Danger

.rubocop_todo.yml, CHANGELOG.md, lib/grape.rb, lib/grape/dsl/parameters.rb, lib/grape/endpoint.rb, lib/grape/exceptions/validation_array_errors.rb, lib/grape/validations/attributes_iterator.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/types/build_coercer.rb, lib/grape/validations/validators/base.rb, spec/grape/validations/validators/coerce_spec.rb, spec/grape/validations_spec.rb
Error messages for arrays was totally broken. It always returns index 0 and detect errors only for first entry in Array. You may cherry-pick to master first commit from this branch and run specs to see the problem.
Moreover, i have no idea how previous implementation of indicies may work correctly with current ParamsScope implementation (#1218).
Also i've found bug in coercion - look for TODO comment inside diff. Specs aren't green because of this bug.
=> Fix array indicies in error messages.

spec/grape/validations_spec.rb
This confirms the issue raised in this comment: https://github.com/ruby-grape/grape/issues/1131#issuecomment-194126326 by @galkon
It was quite difficult to track down when this issue was occurring because it actually depends on a required `Array` parameter being defined _before_ the `Hash` parameter in the `params` block. Somehow the existence of an `index` is leaking between the parameters.
@galkon and I spent a bit of time trying to find the source of the issue, but decided to open a PR with the spec in case it turned out to be much easier for someone with a deeper familiarity with the codebase.
=> Spec for Array types leaking index into subsequent Hash validations

UPGRADING.md
Extra `}` causes `SyntaxError`.
=> Fix typo in UPGRADING.md

CHANGELOG.md, lib/grape/middleware/stack.rb, spec/grape/middleware/stack_spec.rb
I realised that [this commit](https://github.com/ruby-grape/grape/commit/7805dd0076f2b21e2f861665c2774ef1e112190d) broke usages of `insert_before`/`insert_after` with `Grape::Middleware::Error`. For example, this is how I use it:
```
insert_before Grape::Middleware::Error, Grape::Middleware::Logger
```
Since that commit, `Grape::Middleware::Error` is inserted in the middleware stack as `Class.new(Grape::Middleware::Error)`. Then, when we try to insert another middleware before or after it, we get:
```
RuntimeError:
No such middleware to insert before: Grape::Middleware::Error
```
The reason is that we don't recognize the anoymous class that represents `Grape::Middleware::Error` in the stack. This pull-request allows considering the superclass for anonymous classes when comparing …
=> Support inserting middleware before/after anonymous classes in the middleware stack

README.md
I ran a license compatibility check against Grape's gems:  all 20 dependencies are under permissive licenses (MIT or Apache), so definitely check-out as compatible with the MIT license!
The badge here gives a quick indicator that the license is MIT, and that the libraries used are compliant with that.
=> Add MIT license badge to the README

CHANGELOG.md, README.md, lib/grape/locale/en.yml, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
This implements the feature requested in #1485 .
Some notes:
* This PR allows for except to be used exclusively allowing all other values except what is defined in except as well as with values, defining a range and then marking a subset of the range as invalid.
* This PR allows for custom except message outside of the regular validation fail message, but falls back to the regular validation fail message if no ```except_message``` is defined.
* There was slight difficulty maintaining compatibility with allowing values to be passed in to ```values:``` without the ```value:``` key. Please ensure that line 5-8 of values.rb https://github.com/ruby-grape/grape/compare/master...jonmchan:feature/except?expand=1#diff-45b62b4ed0aed7ceff346c347f76570eR8 do not cause any incompatibility issues.
* …
=> implemented except in values validator

.travis.yml, CHANGELOG.md, grape.gemspec
=> Drop ruby-2.0 and mustermann19, use mustermann-grape instead

spec/grape/validations/validators/coerce_spec.rb
This is fine, hashie has added `Hashie::Array` and returns it from a bunch of methods. We inspect the elements in this test, and there should be no downstream effect on users.
=> Fix: expect a Hashie::Array.

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb, spec/grape/validations/validators/values_spec.rb
Wrote a failing test for #1492.
=> Bug - Coercion and Lambda Errors

README.md
Adds [AppSignal](https://appsignal.com) to list of monitoring products that support Grape.
Picks up on Grape instrumentation and works out of the box if you mount Grape on Rails, only a few rackup additions if not.
[Relevant documentation](http://docs.appsignal.com/getting-started/supported-frameworks.html#grape)
=> [documentation] Add appsignal to monitoring products

CHANGELOG.md, lib/grape/validations/validators/allow_blank.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/default.rb, lib/grape/validations/validators/presence.rb, spec/grape/validations/params_scope_spec.rb, spec/grape/validations/validators/allow_blank_spec.rb
This should address both the primary issue identified in #1433, which was related to the ```type``` coercer, and related issues with ```allow_blank```.  In both cases, these validators were being run even when their scopes indicated they should not (since the associated ```given``` criterion had not been met).
=> Skip running param validators inside inactive given blocks (#1433)

CHANGELOG.md, lib/grape/validations/validators/regexp.rb, spec/grape/validations/validators/regexp_spec.rb
Ex. this will work
```
params do
requires :names, type: Array[String], regexp: /^[a-z]+$/
end
```
=> Allow to use regexp validator with arrays

CHANGELOG.md, README.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, spec/grape/dsl/parameters_spec.rb, spec/grape/validations/params_scope_spec.rb
It is a proposal with a working prototype for a group attributes feature. If it makes sense then I will continue working on this PR. Your feedback is welcome. 
I was looking into this issue (https://github.com/ruby-grape/grape/issues/1482) recently. I think the presented use case is common for complex APIs schemas. Currently, if I want to apply the same validator (or the same type) for a several endpoint attributes, then I have to define it for every parameter.
What if we introduce a way of defining common parameter settings? Something like [Rails conditional validations](http://guides.rubyonrails.org/active_record_validations.html#grouping-conditional-validations).
For example, this parameters definition:
```ruby
params do
requires :first_name, type: String, allow_blank: false
requires …
```
=> Feature: add group attributes for parameter definitions

lib/grape/formatter/serializable_hash.rb
=> Use simpler less confusing form of expression

CHANGELOG.md, lib/grape/endpoint.rb, lib/grape/middleware/base.rb, lib/grape/validations/params_scope.rb, spec/grape/api_spec.rb, spec/grape/middleware/formatter_spec.rb, spec/grape/middleware/versioner/param_spec.rb, spec/grape/middleware/versioner/path_spec.rb
New versions of RSpec have warnings turned on by default:
config.warnings = true
I believe these warnings are helpful in general to write better code. However, Grape and Grape Entity are very noisy. I get about 20 lines of warnings for one single test where Grape is involved.
I hope you agree. Many of my changes could also be solved differently for sure. I am happy to discuss and change those cases. I also changed the specs for less warnings and turned them on in the test suite.
=> Avoid noise when code runs with Ruby warnings

CHANGELOG.md, lib/grape/locale/en.yml
Adds `:accept_version_header` as valid setting.
=> Updates `invalid_versioner_option` translation.

.travis.yml, CHANGELOG.md, README.md, lib/grape/dsl/inside_route.rb, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb, spec/grape/dsl/request_response_spec.rb, spec/grape/validations/validators/allow_blank_spec.rb, spec/grape/validations/validators/coerce_spec.rb, spec/spec_helper.rb, spec/support/basic_auth_encode_helpers.rb, spec/support/content_type_helpers.rb, spec/support/integer_helpers.rb, spec/support/versioned_helpers.rb
[Fixnum is deprecated now](https://bugs.ruby-lang.org/issues/12005), so I guess we should drop Fixnum and use Integer instead.
@dblock @dm1try Thoughts?
=> Support ruby 2.4

.rubocop.yml, Appraisals, CHANGELOG.md, gemfiles/rails_edge.gemfile, lib/grape/middleware/versioner/path.rb, spec/grape/middleware/versioner/path_spec.rb
I partially reverted changes and disabled rubocop in the line. Also, I added a spec for this case.
Rubocop seems to have a bug about NumericPredicate.
@dblock @thomas-peyric Thoughts?
=> Avoid failing even if given path does not match with prefix

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, spec/grape/dsl/inside_route_spec.rb
As per #1549, having deletes use 204 as the default status when a body is present causes some issues. Sending a 204 No Content with content will likely surprise some clients, and it causes the [formatter to be skipped](https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/formatter.rb#L25-L26).
This PR adds a check for `@body.present?` so that we only default to 204 No Content when there's actually no content.
=> Use 200 as default status for deletes that reply with content

CHANGELOG.md, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
this bug was introduced in https://github.com/ruby-grape/grape/commit/3540ea25a6cc82a700a572b2c8f483b66302d7e6#diff-45b62b4ed0aed7ceff346c347f76570e
previously, you were able to pass `nil` to an endpoint for an attribute that was marked as optional and had a set array of values. after the above change, this was no longer possible.
=> should be able to pass `nil` to an optional array values param

.travis.yml, CHANGELOG.md
Reference: https://github.com/sickill/rainbow/issues/48
=> Fix Rainbow gem installation failure above Ruby 2.3.3 on Travis-CI

CHANGELOG.md, lib/grape/util/stackable_values.rb
Fixing the performance issue mentioned in issue #1560 by eliminating duplicated calls of `StackableValue#[]` in one-liner conditionals.
=> Avoid duplicated calls in StackableValue#[]

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
I'm working on enforcing declared params usage in my codebase, and in doing so I started running into issues where I thought a declared param should be available via a parent scope, but for some reason wasn't.
This is one of those cases. It works as expected if I remove the route defined just above the namespace 'foo'.
=> Failing test to expose a declared params bug

CHANGELOG.md, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
* Reject any input when value or proc output is empty array
* Properly apply except to array inputs
=> Fix ValuesValidator and simplify code

CHANGELOG.md, README.md, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
This PR adds a new option `test_with` to the `values` validator.  If present, it must be a Proc that accepts a single argument (the param value) and returns a truthy value if the argument is valid.
I don't think this has been explicitly asked for, and one could certainly do the same thing using a custom validator.  But this seemed a little more convenient for simple validations that aren't already handled by the existing built-ins.
This could be an acceptable workaround/solution for #1535 which requests the ability to specify a maximum parameter value.
=> Add test_with option to values validator

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
=> refactor declared and include nil values for missing nested params

CHANGELOG.md, grape.gemspec
=> upgrade mustermann-grape to 1.0.0

CHANGELOG.md, lib/grape/middleware/formatter.rb, spec/grape/endpoint_spec.rb
This changes should fix issue described in #726. 
Default format is used when there is no Content-type.
When Content-type is provided but it's not on the list then the error is thrown.
Normal behavior otherwise.
=> Fix for issue #726

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/validators/values_spec.rb
The checking of `type` and `default` validators in `params_scope.rb` is broken in cases where `values` is a Hash containing only the `except` attribute (and no `value` attribute).  For example both of the following are broken:
```
params do
requires :foo, type: String, values: { except: ['bar', 'baz'] }
requires :foo2, values: { except: ['bar2', 'baz2'] }, default: 'bing'
end
```
=> Bugfix: values without value breaks type and default

lib/grape/dsl/routing.rb, lib/grape/dsl/settings.rb
This PR suppresses the following warning at lib/grape/dsl.
```
RUBYOPT=-w bundle exec rake
/Users/numata/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-0.19.2/lib/grape/dsl/settings.rb:15: warning: method redefined; discarding old top_level_setting
/Users/numata/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-0.19.2/lib/grape/dsl/settings.rb:21: warning: method redefined; discarding old inheritable_setting
/Users/numata/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-0.19.2/lib/grape/dsl/routing.rb:182: warning: method redefined; discarding old routes
```
=> Suppress `warning: method redefined`

CHANGELOG.md, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/base.rb, spec/grape/validations/params_scope_spec.rb
Addresses #1600 and #1602.
Array parameters are handled as a parameter that opens a scope with `type: Array`; `given` opens up a new scope, but was always setting the type to Hash. This patch fixes that, as well as correctly labeling the error messages associated with array fields.
=> Bugfix: Correctly handle `given` in Array params

CHANGELOG.md, lib/grape/dsl/helpers.rb, spec/grape/dsl/helpers_spec.rb
Changing helpers DSL to allow the inclusion of many modules.
This attempts to bring a better readability, since it seems to be
more intuitive to send a list of modules when the message in
question is called `helpers`.
Want to move from a syntax like:
```ruby
helpers MyHelper
helpers MyOtherHelper
```
To a syntax like:
```ruby
helpers MyHelper, MyOtherHelper
```
=> Add ability to include an array of modules as helpers

CHANGELOG.md, spec/grape/validations/validators/coerce_spec.rb
This is commit adds additional specs to make sure Boolean type
is indeed working as expected.
https://github.com/ruby-grape/grape/issues/1551
=> Add extra specs for Boolean type field

Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_1.5.2.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_3.gemfile, gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_edge.gemfile
Build started failing because rack-test was upgraded from 0.6.3 to 0.7.0, which now [supports sending empty arrays](https://github.com/rack-test/rack-test/pull/125). For now just fixing it.
=> Lock rack-test that passes array parameters differently.

CHANGELOG.md, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/base.rb, spec/grape/validations/params_scope_spec.rb
Addresses https://github.com/ruby-grape/grape/issues/1659. The core issue was that param validations are a flat list, and the tree structure was only enforced by the recursion in `should_validate?`. When I moved the dependency check into the actual validator, the structure was no longer respected past one level deep. To resolve, I've added a similar recursive check into `ParamsScope#meets_dependency?`. I also added a few more test cases onto @jnardone's repro to test out the behavior works with arrays and nested arrays.
=> [Bugfix] Handle deeply-nested dependent params

CHANGELOG.md, lib/grape/dsl/settings.rb, spec/grape/api/inherited_helpers_spec.rb
Updating settings code to define `:top_level_setting` with parent's
`:inheritable_setting` when available. This will emulate inheritance,
with its expected capabilities (sharing and overriding).
This fixes #1617
=> Make helpers available in subclasses

CHANGELOG.md, README.md, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
Example:
```ruby
params do
requires :number, type: Integer, values: ->(v) { v.even? && v < 25 }
end
```
Right now, sending a non-numeric string or a nil value for `number` will result in a stack trace because neither String nor NilClass have an `even?` method. One could address this with an additional type check in the proc, but that would result in a lot of extra code that doesn't really contribute to the overall clarity of the declaration.
Instead, we should rescue any StandardError raised from an arity-one values validator proc and treat it as a false result.
=> Rescue StandardError from explicit values validator procs

CHANGELOG.md, lib/grape/validations/types/custom_type_coercer.rb, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
This PR aims to simplify the logic (and expensiveness) of coercion by not coercing the param if it is already a valid value unless a custom coercer is provided, which resolves issues we're run into around JSON until further work can be done to improve the experience.  Relates to #1685
=> Avoid coercion of a value if it is valid

lib/grape/namespace.rb
Fix incredibly minimal typo on `namespace.rb` documentation.
=> Fix incredibly minimal typo on namespace.rb documentation

README.md
With original_exception added in this PR: https://github.com/ruby-grape/grape/pull/1652 the document is stale for custom error format. The README has been updated accordingly.
=> Include original_exception in Readme for custom error formatter

CHANGELOG.md, Dangerfile, Gemfile, README.md
Added danger-toc to verify that the README has a valid TOC.
=> Added danger-toc, verify correct TOC.

README.md
The example referred is too far away to reference it without a link
=> Add link to the example

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb, spec/grape/validations/params_scope_spec.rb
Updating `PostBeforeFilter` module to handle empty given arrays as expected:
returning an empty array instead of an empty hash.
Specs have been taken from #1678 and from [this commit](https://github.com/ruby-grape/grape/commit/696db42c1e6ab6627b18e525a7011900d4740c5d).
=> Fix wrong transformation of empty Array in declared params

README.md
Hashie was [removed as dependency](https://github.com/ruby-grape/grape/commit/1bd1a21525e58768c2188a291488d0b3ba2832c5), so `hashie-forbidden_attributes` should not be installed anymore.
=> Removing references to `hashie-forbidden_attributes` from readme

CHANGELOG.md, README.md, lib/grape/validations/types.rb, lib/grape/validations/types/build_coercer.rb, lib/grape/validations/types/custom_type_collection_coercer.rb, spec/grape/validations/validators/coerce_spec.rb
Hi @dblock and @javmorin!
This implements support for "`type: Array[type that responds to .parse]`", as discussed in #1700. `CustomTypeCoercer` is leveraged, so the type may also implement `coerced?` or `parsed?` to implement custom type-checking (or also `call`, which I admit seems a bit weird in this instance).
Supporting `type: Array[Virtus::Attribute subclass]` should also be possible but I think it needs some different plumbing to make it work. From the discussion it wasn't clear to me that there's anyone who is specifically looking for it, or if this PR would make it redundant. Let me know if there's any interest and I can take a look at it.
Supports `Set` declarations as well as `Array`. `Hash` didn't make much sense to me in this context but if anyone has a usage example in mind I …
=> Coerce collections of parseable types

CHANGELOG.md, README.md, spec/grape/middleware/exception_spec.rb
Addresses `rescue_from :all` documentation aspect of https://github.com/ruby-grape/grape/issues/1713
=> `rescue_from :all` documentation fix

CHANGELOG.md, lib/grape/endpoint.rb
This is an attempt to resolve #1672.
Benchmark script:
```
require 'grape'
require 'benchmark/ips'
Benchmark.ips do |ips|
ips.report('class_load') do
class API < Grape::API
prefix :api
version 'v1', using: :path
get '/' do
'hello'
end
end
end
end
```
Before:
```
Warming up --------------------------------------
class_load   590.000  i/100ms
Calculating -------------------------------------
class_load      5.589k (±10.3%) i/s -     27.730k in   5.029428s
```
After:
```
Warming up --------------------------------------
class_load   860.000  i/100ms
Calculating -------------------------------------
class_load      8.761k (±13.6%) i/s -     43.000k in   5.035511s
```
=> Refactor #generate_api_method to improve performance

.rubocop_todo.yml, CHANGELOG.md, lib/grape/dsl/settings.rb, spec/grape/api_spec.rb
Parent and child classes were pointing to the same inheritable setting creating an infinite loop when retrieving values. Fixes #1683 
This was a regression introduced with commit https://github.com/ruby-grape/grape/commit/2c4d5740234da6b96c668e35de4384d0a5d1a8a6.
=> Fix infinite loop when mounting endpoint with same superclass

CHANGELOG.md, lib/grape/dsl/parameters.rb, spec/grape/validations/params_scope_spec.rb
When using `given` and the paramter type is a Hash,
a Grape::Exceptions::UnknownParameter is thrown. This is a wrong behavior
due to the fact that the method `declared_param?(param)` do not deal
properly with params that are hashes (even after flattening the
declared params).
This commit fixes this by checking if the param is a Hash and thus
returning its first key. This approach was already used in other part of
the code, so it was extracted and reused on `declared_params?(param)`.
=> Fix exception being thrown when dependent parameter is a Hash

CHANGELOG.md, lib/grape/exceptions/base.rb, spec/grape/exceptions/validation_errors_spec.rb
https://github.com/ruby-grape/grape/issues/1735
=> Ensure the value of default option must be a string when calling I18n.t

CHANGELOG.md, README.md, lib/grape/middleware/error.rb, spec/grape/middleware/exception_spec.rb
=> Allow rescue from non-StandardError exceptions

CHANGELOG.md, lib/grape.rb
Fix #1663 
Routes are already being eagerly loaded by `grape/lib/grape/api.rb:1`.
=> Removing Router from autoload, API already loads it

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
`include_missing` currently includes aliased parameters even if they're not specified. The existing test for `include_missing` was also broken, it passed regardless of the value of `include_missing`.
=> Fix include_missing for aliased parameters

CHANGELOG.md, README.md, lib/grape/middleware/error.rb, spec/grape/middleware/exception_spec.rb
This continues to address issues discussed in #1713 and #1745.
@dm1try recently [added the ability to explicitly rescue non-StandardError exceptions](https://github.com/ruby-grape/grape/pull/1749) but I found that his solution required a block to be provided in order to handle exceptions or else it would raise an error due to no handler being found. This PR corrects that by re-using the existing `find_handler` and `rescuable?` logic, with some minor modifications to account for `Exception` being rescued instead of `StandardError`. This meant that the additional `rescue Exception` block could go away completely.
**Edit:**  I forgot that @dm1try recommended we deprecate the use of `:all` so this additional option (`rescue_from :exception` - removed from PR after further discussion) is …
=> Allow rescue from non-`StandardError` exceptions to use default error handling

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/api/shared_helpers_exactly_one_of_spec.rb
Tentative fix for #1288 - not sure whether it is the right approach but the specs are green :wink:
I can't shake the feeling that there's some unnecessary complexity in combination with the changes from #1625 so I'm open to suggestions.
=> Fix shared params with exactly_one_of

.rubocop.yml, CHANGELOG.md, lib/grape/middleware/error.rb, spec/grape/api_spec.rb
This pull request fixes Grape exception handling for the following case:
```ruby
class App < Grape::API
rescue_from :grape_exceptions
rescue_from Grape::Exceptions::ValidationErrors do |error|
error!('redefined', 403)
end
params { requires :foo, type: String }
get('/') { 'Hello' }
end
```
I reworked `Grape::Middleware::Error` a bit:
* the code is easier to follow now
* it works faster because we iterate over `options[:rescue_handlers]` and `options[:base_only_rescue_handlers]` only once
* it allocates less garbage
* fixed another covert bug: `options[:base_only_rescue_handlers]` should have higher priority than `options[:rescue_handlers]` because it is more restrictive
=> Grape exception handling

.travis.yml, Appraisals, CHANGELOG.md, README.md, gemfiles/rails_edge.gemfile, lib/grape/middleware/formatter.rb, spec/grape/endpoint_spec.rb
A good portion of a grape API response is currently uninstrumented — when `endpoint_run.grape` closes, the response bodies still haven't been serialized or rendered into their appropriate templates. Adding `format_response.grape` instrumentation will allow us to measure time spent in this portion of the request.
=> Instrument serialization and rendering as 'format_response.grape'

CHANGELOG.md, grape.gemspec
Otherwise Grape::VERSION might refer to another, e.g.,
system wide installed gem version
=> Fix expanding LOAD_PATH in gemspec

CHANGELOG.md, lib/grape/middleware/error.rb, spec/grape/api_spec.rb, spec/grape/middleware/exception_spec.rb
When calling into an API specifying a crafted format that is HTML,
the returned error renders the HTML back to the user, causing a potential XSS
issue.  For example:
http://example.com/api/endpoint?format=%3Cscript%3Ealert(document.cookie)%3C/script%3E
Renders as html:
The requested format '<script>alert(document.cookie)</script>' is not supported.
When an error generates html back to the user, make sure it's properly escaped.
Fixes issue #1762
=> When returning an HTML error, make sure it's safe

README.md
Fixes inconsistency in style of one example.
=> Fixes examples syntax

CHANGELOG.md, README.md, UPGRADING.md, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_1.5.2.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_3.gemfile, gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_edge.gemfile, lib/grape/middleware/formatter.rb, lib/grape/version.rb, spec/grape/endpoint_spec.rb, spec/grape/middleware/formatter_spec.rb
Noticed that for requests where bodies are present (i.e. PUT, POST, PATCH, etc.), that if the content type header was something unsupported that a 406 would be returned. Reading over the original [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt), a 415 should be used when a request entity is not in a supported format, but currently a 406 is returned. It seems like it should be as simple as changing [this logic](https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/formatter.rb#L97-L99).
=> Use 415 status for request bodies of unsupported media type

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
Spec to display behavior of #1769 (as requested in that issue)
=> Fix param aliases within 'given' blocks

CHANGELOG.md, lib/grape/dsl/middleware.rb, spec/grape/api_spec.rb, spec/grape/dsl/middleware_spec.rb
Adds the ability for a user to insert a middleware at a specific point in the middleware stack using the `insert` method.
First commit demonstrates failing integration test case. Second fixes it. Recommended to step through.
In the README of this project it is documented that a user can insert a middleware at a specific point in the stack using the `.insert` method. 
Notable passage:
```
You can add your custom middleware with use, that push the middleware onto the stack, and you can also control where the middleware is inserted using insert, insert_before and insert_after.
```
Notable example:
```ruby
class CustomOverwriter < Grape::Middleware::Base
def after
[200, { 'Content-Type' => 'text/plain' }, [@options[:message]]]
end
end
class API < Grape::API
use Overwriter
insert_before …
```
=> Add documented but not implemented feature so a user can insert a middleware at a specific point in the stack

CHANGELOG.md, lib/grape/endpoint.rb, spec/grape/api/routes_with_requirements_spec.rb
Fix spec in #1787 
This was a bug introduced by commit 9f4ba67. 
The commit replaces [options[:route_options].clone.merge(...)](https://github.com/ruby-grape/grape/commit/9f4ba67#diff-8e15cddb80f42ca7d43872846d80ecbeL176) with [options[:route_options].clone.reverse_merge(...)](https://github.com/ruby-grape/grape/commit/9f4ba67#diff-8e15cddb80f42ca7d43872846d80ecbeR179).
That causes disappear of the requirements in namespace.
=> Fix route requirements bug

CHANGELOG.md, README.md, lib/grape/dsl/desc.rb, spec/grape/dsl/desc_spec.rb
Fix #1789.
Support `summary`, `hidden`, `deprecated`, `is_array`, `nickname`, `produces`, `consumes`, `tags` options in desc block.
```ruby
desc 'Get users' do
summary 'summary'
hidden false
...
end
```
=> Support more options in desc block

CHANGELOG.md, lib/grape/middleware/versioner/header.rb, spec/grape/middleware/versioner/header_spec.rb
We have observed situations where our API has received a request from a network scanner that has an improperly formatted Accept header.  In these cases, `Rack:Accept::Header.parse_media_type` returns an empty array (https://github.com/mjackson/rack-accept/blob/master/lib/rack/accept/header.rb#L42) and `subtype` is set to `nil`.
This PR checks that we actually received a subtype before checking against the vendor and version regexes.
=> Handle improper Accept headers

CHANGELOG.md, README.md, lib/grape/exceptions/base.rb, spec/grape/exceptions/base_spec.rb, spec/spec_helper.rb
- If I18n enforces available locales, in case of an exception return the translation key if the fallback locale is not supported
- Set I18n.enforce_available_locales to `true` in the spec helper because this reflects the default settings for a standard Rails app
=>  Fix crash when available locales are enforced but fallback locale unavailable

README.md
This should fix mixed-content issue in [YARD documentations](https://www.rubydoc.info/gems/grape/1.1.0).
=> [skip ci] Use HTTPS in README

.yardopts
This should fix the broken logo in https://www.rubydoc.info/gems/grape/1.1.0.
=> Add YARD configuration

CHANGELOG.md, README.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
Fixes #1808 
> It seems like we cannot access to the value inside the proc for an alias param
> 
> ```ruby
> requires :type, as: :action
> given type: ->(val) { ActionService::ACTIONS.include?(val) } do #val not present inside the proc
>   requires :comment, type: String
> end
> ```
The root cause is `as: :action` alias would change `params` from `{ type: 'some type' }` to `{ action: 'some type' }` in as validator.
https://github.com/ruby-grape/grape/blob/3bb835a747f8ef2a9542ef2e6b66c795f377dd87/lib/grape/validations/validators/as.rb#L9-L12
When checking `->(val) { ActionService::ACTIONS.include?(val) }` in the following snippet(line 61), dependency_key is still `:type`, so params[:type] is nil because the params is changed in previous validator. …
=> Fix alias on dependent param bug

CHANGELOG.md, lib/grape/dsl/parameters.rb, spec/grape/validations/params_scope_spec.rb
Fixes #1800. Continue of #1804.
`given` will check whether attribute is declared in its scope.
If not, it [raises an error](https://github.com/ruby-grape/grape/blob/b8b85af12ad4860b6ee4ae2074f864a849400209/lib/grape/dsl/parameters.rb#L202-L208).
```ruby
optional :a
given a: ->(val) { val == 'a' } do
optional :b
given b: ->(val) { val == 'b' } do
requires :c
end
end
```
In the example, [`optional :a` creates a scope](https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/parameters.rb#L160). [`given a: ...` creates
another scope](https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/parameters.rb#L207), which parent scope is the one created by `optional :a`,
and [attributes `:b` declared in `optional :b` is pushed to parent …
=> Support nested dependent parameters

.travis.yml, CHANGELOG.md, gemfiles/rack_1.5.5.gemfile, gemfiles/rails_3.gemfile, gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, spec/grape/integration/rack_spec.rb
* Update ruby, rails, rack version in travis.
* Add ruby 2.5 support, drop 2.2.
The new version of ruby is released.  Update travis settings.
Reference: https://www.ruby-lang.org/zh_tw/
=> Add ruby 2.5 support, drop 2.2.

spec/grape/validations/params_scope_spec.rb
Add spec for #1681. The issue seems already fixed.
=> Add spec for default value in given block

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
Related to the issue raised here:
https://github.com/ruby-grape/grape/issues/1815
Uses the following failing specs:
https://github.com/ruby-grape/grape/pull/1816
=> Fixes methods defined on included modules after remountable APIs

lib/grape/api.rb
In order to properly use the autoloader, we do not want to delegate `anonymous?` to the instance.
This should fix most remaining issues with the autoloader in master: https://github.com/ruby-grape/grape/issues/1815
Sorry for the lack of specs. It's really hard to reproduce without setting up a new project.
This was tested using: https://github.com/myxoh/testing-grape/commits/master
(If you run rspec it crashes, when you add this commit, it stops crashing)
=> Fixes the issue with the autoloader #1815

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
Thanks to https://github.com/ruby-grape/grape/issues/1829 I've realized that actually I could just avoid overriding all of the class methods, other than new, on the specs
=> restores self_sanity Addresses #1829

CHANGELOG.md, lib/grape/dsl/desc.rb, spec/grape/dsl/desc_spec.rb
Adds support for `security` in `desc` block.
Proposing the change since [options hash parameters are marked as deprecated](https://github.com/ruby-grape/grape/blob/v1.2.1/lib/grape/dsl/desc.rb#L58) and the bug in ruby-grape/grape-swagger#706 prevents using both (options are not merged into the block).
```Ruby
desc `Create User` do
security [
]
end
````
Includes some minor formatting changes in the spec (in separate commits) and I didn't update the `README.md` since it [already points to `grape-swagger` for more info](https://github.com/ruby-grape/grape#describing-methods).
Related to #1791 and (slightly) to ruby-grape/grape-swagger#729.
=> Support security in desc block

CHANGELOG.md, lib/grape/validations/types/file.rb, spec/grape/validations/validators/coerce_spec.rb
=> fix: enforce tempfile to be a Tempfile object

.travis.yml
test only a single job and allow failures
ref https://github.com/ruby-grape/grape/pull/1856#issuecomment-459153246
=> CI, relax rules for "rack_edge" builds

.rubocop_todo.yml, CHANGELOG.md, README.md, lib/grape/dsl/callbacks.rb, lib/grape/dsl/request_response.rb, lib/grape/endpoint.rb, lib/grape/middleware/error.rb, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb
https://github.com/ruby-grape/grape/issues/1865
Motive: Sometime we do things like logging, or open sessions, or other actions during an API request and we want to make sure those actions are wrapped up afterwards.
This introduces a DSL way of handling this after every request on an API
=> Allows for a block of code to always run after the endpoint

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
Fix issue with empty headers after `error!` method call https://github.com/ruby-grape/grape/issues/1719
It happened when headers were set in `before` block or endpoint body.
=> [#1719] Fix missing headers before error! call

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
```rb
params do
requires :foos, type: Array do
optional :bar
given :bar do
requires :baz
end
end
end
get '/test' { 'ok' }
```
```
client.get('/test', foos: ['abc'])
#=> NoMethodError (undefined method `with_indifferent_access' for "abc":String)
```
=> Fix NoMethodError with none Hash params

README.md
Adding missing `post /comments/votes` to the explanation of remounting endpoints.
=> Add missing endpoint to Remounting example.

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
I had not included a file and so a constant was missing. I did not receive the correct error as the custom `const_missing` was throwing an error of its own.
This PR resolves that for me.
```bash
NameError:
undefined local variable or method `parent' for MyApiClass
```
=> Fix const errors being hidden by bug in const_missing

README.md
For Rails >=5.2, modification of `application.rb` is not necessary.
For Rails 6.0 beta, the new `Zeitwerk` loader brings some breaking changes. `API` in our Twitter::API example now has to be explicitly set as an acronym in `inflections.rb`. 
Issue: https://github.com/ruby-grape/grape/issues/1878
=> Update mounting instructions for Rails 5&6 in README

README.md, lib/grape/dsl/inside_route.rb, lib/grape/endpoint.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/as.rb, spec/grape/endpoint_spec.rb, spec/grape/validations/params_scope_spec.rb
Closes #1875. 
This PR is to rename misleading term "alias" to "renaming". Changes cover docs and variables naming.
=> Change misleading naming of alias

CHANGELOG.md, lib/grape/api.rb, spec/grape/integration/rack_spec.rb
By calling: 'call' on the first mounted instance rather than the base instance (which is never mounted) which will have the environment information as to where it was mounted
This addresses the underlying issue raised by: https://github.com/ruby-grape/grape/issues/1892
=> Makes sure Grape::API behaves as a Rack::App 

CHANGELOG.md, lib/grape/dsl/validations.rb, lib/grape/endpoint.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/validator_factory.rb
While doing some profiling for my organisation Rails app, l have found some quick wins to improve the memory of this gem. 
The major change was to refactor the `Grape::Validations::ValidatorFactory` to use singleton methods instead of instances.
I have done some tests to see how many bytes I can save by params.
```ruby
require 'memory_profiler'
report = MemoryProfiler.report do
require 'grape'
class EchoAPI < Grape::API
version 'v1'
format :json
prefix :api
params do
requires :message, type: String # I use a loop to try many param
end
post :echo do
params[:message]
end
end
end
report.pretty_print(to_file: 'grape.txt')
```
```
#
#
#
```
```
#
#
```
```
#
#
```
The result is ~1010 bytes per param.
mb save per params = **0.00101** * x + 0.0213
=> Memory profiling fix, Refactor ValidatorFactory

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
Previously it wasn't possible to rename attributes that have a block: https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/parameters.rb#L134. Known side effects: renamed keys aren't removed from `params` and cause duplication there, but `declared(params)` keeps only the correct keys.
This PR doesn't fix the problem with duplication of keys in the `params` hash when a deeply nested attribute or an attribute with a block is renamed. Here we remove renamed keys https://github.com/ruby-grape/grape/blob/master/lib/grape/endpoint.rb#L327-L332, but the only place we mark keys for deletion is here: https://github.com/ruby-grape/grape/blob/master/lib/grape/validations/params_scope.rb#L128 and it doesn't cover the case of hash/array attributes with block or even ordinary nested …
=> Fix Hash params renaming

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/api.rb, lib/grape/api/instance.rb, lib/grape/eager_load.rb, spec/grape/api_spec.rb
Partially addresses the issues raises on: https://github.com/ruby-grape/grape/issues/1902
The way it does so is it allows a method `compile!` that makes a large percentage of the work to warm up the API on load time.
More work is needed before the API is 100% warmed up.
--------------
Taking suggestions as to how best to test this
=> [AutoLoad] Autoload Fixes

CHANGELOG.md, README.md, lib/grape/api.rb, spec/grape/api_spec.rb
Still work in progress... includes an intentionally failing test for the inheritance of config to mounted APIs, which I am totally unsure of how to implement and would really like some help with :)
Also if the method name is appropriate. I prefer `with_configuration(hash)` but @myxoh thought of `with(configuration: hash)`.
Todo list:
Thanks!
=> Add .configuration to Grape::API (fixes #1906)

CHANGELOG.md, lib/grape/validations/validators/at_least_one_of.rb, spec/grape/validations/validators/at_least_one_of_spec.rb, spec/grape/validations_spec.rb
Unlike other validators `Grape::Valiations::AtLeastOneOfValidator` didn't wrap params into a scope (namespace) for errors when params were nested.
Closes #1849
=> AtLeastOneOfValidator properly treats nested params in errors

Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_3.gemfile, gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_edge.gemfile, spec/grape/validations/validators/coerce_spec.rb, spec/grape/validations_spec.rb
As it was mentioned in #1658 empty arrays aren't ignored anymore, so specs should be updated.
Is a note in the changlelog required for this PR? It isn't a new feature, neither a bugfix :thinking:  
Closes #1656
=> Upgrade rack-test to 1.1.0

.rspec, CHANGELOG.md, spec/grape/endpoint_spec.rb, spec/grape/exceptions/base_spec.rb, spec/grape/middleware/formatter_spec.rb, spec/grape/validations/validators/coerce_spec.rb
This PR enables spec randomization by default. It also fixes a couple of failures discovered after enabling `--order=rand` :nerd_face:
=> Run specs in random order

CHANGELOG.md, benchmark/nested_params.rb, lib/grape/endpoint.rb, lib/grape/error_formatter.rb, lib/grape/exceptions/validation_errors.rb, lib/grape/formatter.rb, lib/grape/parser.rb, lib/grape/util/base_inheritable.rb, lib/grape/util/inheritable_values.rb, lib/grape/util/reverse_stackable_values.rb, lib/grape/util/stackable_values.rb, lib/grape/validations/validators/base.rb
There were a few places where hashes could be mutated without side effects, they already work with copies of original hashes. So, `merge!` replaced some of `merge` calls.
Also, `Grape::Util::StackableValues`, `Grape::Util::ReverseStackableValues` and `Grape::Util::InheritableValues` got a base class which keeps common methods
to avoid duplication. Besides, that a `[]` and `keys` methods were optimized to allocate less arrays when it is possible.
There is an additional benchmark which measures more complex scenario. Unfortunately, there isn't noticeable difference in performance between the master and this change. However, I also profiled the same endpoint as the benchmark has.
Before this change:
Measure Mode: memory
Thread ID: 47216803207600
Fiber ID: 47216805628400
Total: 40536.000000 …
=> micro optimizations in allocating hashes and arrays

CHANGELOG.md, spec/grape/middleware/formatter_spec.rb
A small fix to keep up with the new changes in rack: https://github.com/rack/rack/commit/6746515453a44cc6268c46d525158278cf96307d#diff-7c1a24d5b2fe58a6f925c7cacc6c55e7L558-R558
The format of the object with the possible statuses has changed in a recent release, which breaks the rack-edge appraisal, so this PR fixes it.
=> Update access to rack constant

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/middleware/auth/base.rb, lib/grape/middleware/base.rb, lib/grape/middleware/helpers.rb, spec/grape/middleware/base_spec.rb
This is a feature suggestion.
Recently, working with Grape and writing some `rescue_from` handlers, I've encountered a need to access the request params, headers, and some other stuff how it was in the original controller method.
It was possible, but there was no documented and elegant way to do it. And I needed to go through the Grape source code to figure out a way to reach it. 
With this change, we can save effort and time for other clients by preventing the need to rediscover this. It is useful not only for the error handling, but also for every piece of the middleware, including formatters, and any custom middleware inherited from Grape::Middleware::Base.
This PR adds the actual helper method for accessing the context, tests, and documentation for it.
=> Helper method to access controller context in middleware

CHANGELOG.md, lib/grape.rb, lib/grape/validations/attributes_iterator.rb, lib/grape/validations/multiple_attributes_iterator.rb, lib/grape/validations/single_attribute_iterator.rb, lib/grape/validations/validators/all_or_none.rb, lib/grape/validations/validators/at_least_one_of.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/default.rb, lib/grape/validations/validators/exactly_one_of.rb, lib/grape/validations/validators/multiple_params_base.rb, lib/grape/validations/validators/mutual_exclusion.rb, spec/grape/exceptions/validation_errors_spec.rb, spec/grape/validations/multiple_attributes_iterator_spec.rb, spec/grape/validations/single_attribute_iterator_spec.rb, spec/grape/validations/validators/all_or_none_spec.rb, spec/grape/validations/validators/at_least_one_of_spec.rb, spec/grape/validations/validators/exactly_one_of_spec.rb, spec/grape/validations/validators/mutual_exclusion_spec.rb, spec/grape/validations_spec.rb
Previously multiple params validators returned messages without considering the scope.
For example, in case of hash params:
`{ "param_1,param_2": 'error message' }`
instead of:
`{ "hash[param_1],hash[param_2]": 'error message' }`
Or in case of arrays, indexes were ignored completely:
`{ "param_1,param_2": 'error message' }`
instead of:
`{ "array[1][param_1],array[1][param_2]": 'error message' }`
This PR fixes it by using `AttributesIterator` in a similar way to `Grape::Validations::Base`.
Also the specs are refactored to work in a similar way to the ordinary single-parameter validations.
=> Fix error messages for nested multiple params validations

README.md
This adds some more documentation, that was partly implicitly covered
by the Basic Usage example but partly was only to be got by the method
documentation. As this is an essential part of the DSL this it added for
the new users conveniance. At least I was missing the info.
This is my first draft, so please tell me whether I'm missing something, or got something wrong!
=> Expand route documentation in the README

CHANGELOG.md, README.md, lib/grape.rb, lib/grape/api.rb, lib/grape/api/instance.rb, lib/grape/util/lazy_block.rb, lib/grape/util/lazy_value.rb, spec/grape/api_remount_spec.rb
This PR is motivated by a bug I've introduced on our system.
The problem, when you are trying to waterfall a configuration, is that `LazyValue` doesn't play nicely inside an expression so this code
```ruby
value = configuration[:attribute] || 'default_value' 
```
Is evaluated when the class is load as: configuration[:attribute] => LazyValue || 'default_value' => LazyValue
Which means that even when you mount the API with `attribute: nil` the value will equal `nil` rather than `'default_value'` as a developer might expect.
To mitigate this, I've introduced a lazy block, so you are able to put that expression within a `mounted` block which will only be evaluated when the API is mounted, and furthermore, will prevent methods using the response of the expression to running before the API is …
=> [LazyBlock] Allows using complex expressions with configuration

README.md
Add a documentation hint for mount configuration.
I know it might sound like a newbie issue (and it is, probably) but I just spent half an hour trying to find out where my configuration was.
Feel free to remove if it's not relevant as it's 100% Ruby matter and 0% Grape. 
¯\_(ツ)_/¯
I didn't write a changelog as it's not a feature, also feel free to ask for one. :)
BTW thank you so much for this incredible gem, love it!
=> Documentation hint for mount configuration

CHANGELOG.md, grape.gemspec
=> Fix bloat in released gem.

CHANGELOG.md, grape.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/grape), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
=> Add project metadata to the gemspec

CHANGELOG.md, lib/grape/http/headers.rb, lib/grape/router.rb, lib/grape/router/route.rb
I ran a memory profiling (memory_profiler gem) on my app by hitting our Grape api first. I found it odd that it retains a bunch of http verbs when they are defined as const in Grape::Http::Headers :
```log
354  "HEAD"
353  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/route.rb:67
1  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:30
352  "GET"
351  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/route.rb:67
1  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:30
168  "POST"
107  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/route.rb:67
60 …
```
=> Retained Grape::Http::Headers in memory instead of new ones created.

CHANGELOG.md, lib/grape/router.rb, lib/grape/router/attribute_translator.rb
Still memory profiling
```log
Allocated String Report
-----------------------------------
7640  "d"
3820  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/attribute_translator.rb:16
3820  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/attribute_translator.rb:18
1248  "s"
624  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/attribute_translator.rb:16
624  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/attribute_translator.rb:18
936  "p"
468  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router/attribute_translator.rb:16
468 …
```
=> AttributeTranslator optimization

CHANGELOG.md, lib/grape/router.rb
While memory profilling our app, I found these strange memory allocations :
```log
1442  "(?<_"
974  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:41
468  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:53
983  ")"
974  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:41
9  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/mustermann-grape-1.0.0/lib/mustermann/grape.rb:20
974  ">"
974  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:41
468  ">)"
468  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape-1.2.6/lib/grape/router.rb:53
12 …
```
=> Regex string allocation

CHANGELOG.md, lib/grape/api/instance.rb, spec/grape/api/instance_spec.rb
Addresses issue raised here: https://github.com/ruby-grape/grape/issues/1945
The cause of the issue is the introduction of the `LazyBlock` where blocks would only be excecuted on properly mounted instances, the side effect is for people using just `Instance` they had no base at all.
=> Fixes issue by checking if there's a base is there at all

CHANGELOG.md, lib/grape/validations/attributes_iterator.rb, lib/grape/validations/single_attribute_iterator.rb, lib/grape/validations/validators/base.rb, spec/grape/validations/single_attribute_iterator_spec.rb
Integers don't respond to the `empty?` method. It caused issue with optional params as described in #1847.
=> Careful check for empty params

CHANGELOG.md, grape.gemspec
From the PR discussion: https://github.com/ruby-grape/grape/pull/1920#issuecomment-569010623
Ruby 2.7.0 was released December 25, 2019, and has some noisy [deprecation messages about keyword arguments](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/). 
Thanks to PR #1920 we migrated from Virtus to dry-types, but set too strict version for it - `~> 1.1.1`, so new versions of the dry-types gem couldn't be used with Grape (like current 1.2.2 from December 14, 2019). Also 1.1.x versions of dry-types produces a lot of deprecation warnings with Ruby 2.7 that can be too noisy.
I relaxed dependency version to `>= 1.1` and tested it against latest dry-types version on rubygems.org and everything seems to be good.
=> Relax dry-types dependency version

CHANGELOG.md, lib/grape/validations/params_scope.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
When `allow_blank` is true, the values validator shouldn't raise `Grape::Exceptions::Validation` in case of a blank value.
Fixes https://github.com/ruby-grape/grape/issues/1604
=> Consider the allow_blank option in the values validator

CHANGELOG.md, lib/grape/exceptions/validation.rb
As from the title: small fix for kwargs in `Grape::Exceptions::Validation` class and typo fix in changelog.
=> Small Ruby 2.7 + changelog fixes

.travis.yml, gemfiles/rack1.gemfile, gemfiles/rack2-0.gemfile, lib/grape/middleware/base.rb, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb, spec/grape/integration/rack_spec.rb, spec/grape/middleware/formatter_spec.rb, spec/spec_helper.rb
And update specs/expand testing.
=> Align implementation with Rack SPEC

CHANGELOG.md, lib/grape/validations/validators/values.rb, spec/grape/validations/validators/values_spec.rb
Fixes #1577 .
When we check whether a value is given or not, it is safer to look for `nil`, there are cases when `false` is ok value.
=> The values validator must properly work with booleans

CHANGELOG.md, README.md
Fixes typos in README: `Middlware` => `Middleware`
=> Fixes typos in README

CHANGELOG.md, lib/grape/middleware/stack.rb, spec/grape/middleware/stack_spec.rb
ref #1967
~it fails on ruby 2.7.0 because of an "extra" argument(the proc) is forwarded~(FIXED)
`public_send(operation, *args, &args.pop)` works differently in ruby 2.7.0, `args` is not modified by `pop` if placed in the method call before the `pop`; though it looks more expected to me.
=> fix proc forwarding in Middleware::Stack#merge_with for ruby 2.7.0

CHANGELOG.md, lib/grape/validations/types/primitive_coercer.rb, spec/grape/validations/validators/coerce_spec.rb
This PR attempts to fix coercion of params to BigDecimal as per https://github.com/ruby-grape/grape/issues/1969
=> BigDecimal coercion

lib/grape/validations/types/primitive_coercer.rb, spec/grape/validations/types/primitive_coercer_spec.rb
Unit tests better focus on corner cases in this case than integration tests which might be too high level.
I guess changelog isn't required for this.
=> more tests for Grape::Validations::Types::PrimitiveCoercer

CHANGELOG.md, lib/grape.rb, spec/spec_helper.rb, spec/support/eager_load.rb
=> Be sure classes/modules listed for autoload really exist

CHANGELOG.md, lib/grape/validations/types/file.rb, spec/grape/validations_spec.rb
=> Skip validation for a file if it is optional and nil

spec/grape/validations/types/primitive_coercer_spec.rb, spec/grape/validations/validators/coerce_spec.rb
What do you think about unit tests for such cases? :slightly_smiling_face:
=> more unit tests for coercion

CHANGELOG.md, lib/grape/validations/validators/exactly_one_of.rb, spec/grape/exceptions/validation_errors_spec.rb, spec/grape/validations/validators/exactly_one_of_spec.rb, spec/grape/validations_spec.rb
Breaking change at revision 96e4e1044e73e64414af709352b270ab4f88c864
Before the breaking change specs only tested a `Grape::Exceptions::Validation` error was returned rather than the message itself so this fell through when changed over to the new `MultipleParamsBase` code.
=> Re-add exactly_one_of mutually exclusive error message

CHANGELOG.md, lib/grape/exceptions/base.rb, lib/grape/exceptions/validation_errors.rb
Hi, Thank you for your work here 🙏.
This PR is an attempt to address: https://github.com/ruby-grape/grape/issues/1954. 
As mentioned in the issue, Ruby 2.5 add a `full_message` to Exception (https://ruby-doc.org/core-2.5.0/Exception.html#full_message-method). Grape overrides this and to stop that this PR removes the `full_message` private method.
=> refactored the full_messages method and stop overriding full_message

CHANGELOG.md, lib/grape/api/instance.rb, lib/grape/router.rb
Hi,
While profiling my app, I found this :
```log
266 "GET, HEAD"
266 /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape1.3.0/lib/grape/api/instance.rb:230
60  "POST"
60  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape1.3.0/lib/grape/api/instance.rb:230
30  "PATCH"
30  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape1.3.0/lib/grape/api/instance.rb:230
22  "GET, POST, HEAD"
22  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape1.3.0/lib/grape/api/instance.rb:230
20  "GET, PATCH, HEAD"
20  /Users/eproulx/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/grape1.3.0/lib/grape/api/instance.rb:230
```
I figured that joining allowed headers while not actually requesting OPTIONS is a small waste of memory.  Instead, we could …
=> Lazy join over allow headers

CHANGELOG.md, README.md
I found a typo in the README ("trigered" instead of "triggered") so I thought I'd be helpful. After that I fixed another typo so hopefully this is merge-worthy :)
=> Fix typo in README

CHANGELOG.md, Gemfile, lib/grape/api.rb, lib/grape/dsl/helpers.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/parameters.rb, lib/grape/dsl/routing.rb, spec/grape/api_spec.rb, spec/grape/validations/instance_behaivour_spec.rb, spec/spec_helper.rb
* Add warnings enablement to spec_helper.rb to see future warnings
* Use instance_variable_defined? to clean up not initialized warnings
* Add 'inherited' to NON_OVERRIDABLE list
* Add multi_xml to test dependencies in Gemfile to address spec failure
=> Address some Ruby warnings

CHANGELOG.md, lib/grape/api/instance.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/routing.rb, lib/grape/http/headers.rb, lib/grape/middleware/base.rb, lib/grape/namespace.rb, lib/grape/path.rb, lib/grape/request.rb, lib/grape/router.rb, lib/grape/router/pattern.rb, lib/grape/util/base_inheritable.rb, lib/grape/util/cache.rb, lib/grape/util/lazy_object.rb, lib/grape/util/reverse_stackable_values.rb, lib/grape/util/stackable_values.rb, lib/grape/validations/params_scope.rb
Hello,
I'm still working on improving string allocations and this PR follows my work.
- I added some lazy lookup tables at some places for a better string allocations.
- I added a lazy object which kind of a proxy for executing code when needed. It's mainly used when building headers for request. I also added a lazy object const that contains converted well known http headers.
- I fixed a small leak in stackable_values for empty arrays. It's now generating empty_array only when needed
- I replaced some %w by actual const
Here's some stats based on our app:
###
Overall Grape object allocations (development environment)
###
```log
Total allocated: 47115631 bytes (437131 objects)
Total retained:  6323963 bytes (16355 objects)
Total allocated: 41291815 bytes (300978 objects)
Total retained: …
```
=> Lazy lookup and lazy object

.rubocop_todo.yml, CHANGELOG.md, lib/grape.rb, lib/grape/api.rb, lib/grape/middleware/versioner/header.rb, lib/grape/middleware/versioner/path.rb, lib/grape/namespace.rb, lib/grape/path.rb, lib/grape/router.rb, lib/grape/router/pattern.rb, lib/grape/router/route.rb, lib/grape/validations/validators/coerce.rb
Hello,
Here are some fixes based on rubocop todo:
- Style/HashTransformValues
- Style/RescueStandardError
- Lint/RedundantRequireStatement
- Performance/RegexpMatch
- Style/MutableConstant
- Lint/DisjunctiveAssignmentInConstructor
=> Rubocop todo fixes

.rubocop_todo.yml, CHANGELOG.md, lib/grape/validations/validators/coerce.rb
Fix Style/RescueStandardError
As discussed @dblock
=> Upgrade coerce behavior when rescuing error.

CHANGELOG.md, lib/grape/router.rb, lib/grape/router/route.rb
I removed the code that retain regexes in Route and Any classes since its union.
```log
Total allocated: 41885240 bytes (308172 objects)
Total retained:  6000260 bytes (11806 objects)
#next version
Total allocated: 41851936 bytes (305115 objects)
Total retained:  3419455 bytes (8907 objects)
```
Almost half total retained :)
=> Drop retained regexes

CHANGELOG.md, lib/grape/util/reverse_stackable_values.rb, lib/grape/util/stackable_values.rb
```log
allocated memory by class
-----------------------------------
15834248  Array
15730608  Hash
6726012  String
3079724  Regexp
202016  MatchData
allocated memory by class
-----------------------------------
15730608  Hash
6726012  String
5870664  Array
3079724  Regexp
202016  MatchData
```
=> Reduced array allocation

CHANGELOG.md, lib/grape/middleware/versioner/header.rb, lib/grape/middleware/versioner/parse_media_type_patch.rb, lib/grape/path.rb, lib/grape/router/route.rb, lib/grape/validations/types/json.rb, lib/grape/validations/validators/regexp.rb, spec/grape/path_spec.rb
```log
allocated memory by class
-----------------------------------
15730608  Hash
6726012  String
5870664  Array
3079724  Regexp
202016  MatchData
allocated memory by class
-----------------------------------
15730608  Hash
6726012  String
5870664  Array
3079724  Regexp
81024  Grape::Router::Route
72936  Grape::Router::Pattern
40520  Grape::Router::AttributeTranslator
38960  Grape::Router::Any
25840  Grape::Path
23376  MatchData
```
=> Reduced MatchData allocation

UPGRADING.md
If `Array[String]` is used without a `coerce_with` block, existing APIs may
quietly fail without explanation. This change to the upgrade
documentation makes that clear.
Closes https://github.com/ruby-grape/grape/issues/2013
=> Add upgrade notice for Array[String]

UPGRADING.md
Previously Vitrus implicitly coerced strings to integers when
Array[Integer] types were used. With dry-types, this is no longer done,
and APIs that expected this behavior will fail with an invalid type
check.  Expand the upgrade docs to include all Array types and an
example for Array[Integer].
=> Add upgrade notice on upgrading all Array types

CHANGELOG.md, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
If an optional parameter has multiple types (e.g. `[File, String]`) and a
`nil` parameter is passed, Grape would previously coerce the value to an
empty `Array`. This can break certain APIs that treat nil values
differently from an empty Array.
To fix this, we refactor the nil handling into a `coerce_nil` method and
remove the special case check for handling an Array of types.
Closes #2018
=> Avoid coercing parameter with multiple types to an empty Array

CHANGELOG.md, lib/grape/validations/types/primitive_coercer.rb, spec/grape/validations/validators/coerce_spec.rb
It may be more useful by using `DryTypes::Params::Decimal`.  Because `DryTypes::Coercible::Decimal` fails coercing `45.1` for json reqeust.
=> Fix Decimal type category

CHANGELOG.md, lib/grape/validations/types/custom_type_coercer.rb, spec/grape/validations/validators/coerce_spec.rb
Previously nil was handled as valid value for coercion for integer parameters.
With refactoring introduced in 1.3.0 integer parameter coerced with a custom method can't coerce to nil any more.
This change reverts back to previous behaviour where coercion to nil was allowed.
=> Fix a regression in coerce_with when coercion returns nil

UPGRADING.md
* Provide an example for taking an existing type and porting it to
the dry-types. This would have saved me some time.
* Removed examples of using `Virtus.model`. It seems confusing to
support dry-types and Virtus at the same time.
Closes #2012
=> Improve UPGRADING.md instructions for custom types

CHANGELOG.md, lib/grape/validations/types.rb, lib/grape/validations/types/build_coercer.rb, lib/grape/validations/types/file.rb, lib/grape/validations/types/json.rb, spec/grape/validations/types_spec.rb, spec/grape/validations/validators/coerce_spec.rb
Users tries to use types provided by Grape as an example how to write custom types. So, it makes sense to treat them as custom.
Besides that, it fixes #1986 where a collection of a custom type wasn't coerced properly.
=> Special types provided by Grape are custom ones

CHANGELOG.md, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
Possible fix for `Float` coercion to `BigDecimal` https://github.com/ruby-grape/grape/issues/2032.
When checking for equality of params, checks both the class and value of params rather than just the value.
/cc: @dblock @dnesteryuk
=> Ensure floats are correctly coerced to bigdecimal

README.md
As it was agreed in https://github.com/ruby-grape/grape/issues/1258 the code example was removed
=> Remove a code example for comparing passwords in Basic authentication

.travis.yml, CHANGELOG.md
Hi,
I just updated ruby versions in travis since there are new versions available since March 31
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/
Thanks
=> Update travis ruby versions

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
I fixed bugs of declared method.
key of options[:route_options][:params] is not considered for nested params.
I changed to these.
* if nested array is nil, declared method return [].
* if nested hash is nil, declared method return {}.
=> Modify declared for nested array and hash

SECURITY.md
Adding a security policy as part of onboarding in #2034. I think 1.2.0 is fine as oldest version we support for security vulnerabilities, given that we had 1-2 in the entire history of Grape.
=> Added SECURITY.md.

CHANGELOG.md, LICENSE, README.md
=> Document TideLift Enterprise support.

CHANGELOG.md, UPGRADING.md, lib/grape/validations/types/array_coercer.rb, lib/grape/validations/types/dry_type_coercer.rb, lib/grape/validations/types/variant_collection_coercer.rb, lib/grape/validations/validators/coerce.rb, lib/grape/validations/validators/default.rb, spec/grape/validations/validators/coerce_spec.rb, spec/grape/validations/validators/default_spec.rb, spec/grape/validations/validators/values_spec.rb, spec/grape/validations_spec.rb
Since #2019, I found a regression (our tests suite fails with 1.3.2) when params type is an `Array` of `Type` and the api is called with a `nil` value. It should return the default value which is `[]`.
=> Fix coerce_nil when Array of Type

CHANGELOG.md, lib/grape/router.rb, lib/grape/router/attribute_translator.rb, lib/grape/router/route.rb
Hi,
I transformed `route` public send to actual methods in `attribute_translator`.  Makes more sense than falling back on `method_missing`.
I also removed `Any` in router and use pure `AttributeTranslator`.
=> Refactor route public_send to AttributeTranslator

CHANGELOG.md, lib/grape/validations/types/primitive_coercer.rb, spec/grape/validations/types/primitive_coercer_spec.rb
Satisfies a pending test in #2045
=> Coerce an empty string to nil in case of the bool type

CHANGELOG.md, lib/grape/validations/types/array_coercer.rb, lib/grape/validations/types/build_coercer.rb, lib/grape/validations/types/dry_type_coercer.rb, lib/grape/validations/types/set_coercer.rb, spec/grape/validations/types/array_coercer_spec.rb, spec/grape/validations/types/primitive_coercer_spec.rb, spec/grape/validations/types/set_coercer_spec.rb
It is a regression which was introduced after migrating to DryTypes. Now, it is again possible to define an array of arrays as a type.
```ruby
params do
requires :skills, type: Array[[String]]
end
```
Fixes #2041
=> coercing of nested arrays

CHANGELOG.md, lib/grape/middleware/base.rb
Addresses https://github.com/ruby-grape/grape/issues/1992.
Before this PR, `Grape::Middleware::Base` is treating the `options` param as keyword args, but it's actually meant as a `Hash` positional argument.
https://github.com/ruby-grape/grape/blob/536622a38ae5ed266477689cdd7afabd92046ed2/lib/grape/middleware/base.rb#L17
The former style, `**options`, prompts a deprecation warning in Ruby 2.7.
`gems/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:158: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
`gems/2.7.0/gems/grape-1.3.3/lib/grape/middleware/base.rb:17: warning: The called method 'initialize' is defined here`.
For a middleware subclass of `Grape::Middleware::Base`, Rack's `use` method will instantiate it with `middleware.new(app, …
=> Treat Middleware::Base#initialize options as Hash.

benchmark/compile_many_routes.rb
This replicates the slowness in compiling routes via Mustermann for 2000
routes.
Part of https://github.com/ruby-grape/grape/issues/1736
```
$ ruby compile_many_routes.rb
Warming up --------------------------------------
Compiling 2000 routes
1.000  i/100ms
Calculating -------------------------------------
Compiling 2000 routes
4.541k (±16.0%) i/s -     20.871k in   4.989357s
```
ruby-prof output:
=> Add a benchmark for API.compile!

CHANGELOG.md, lib/grape/dsl/inside_route.rb, lib/grape/dsl/validations.rb, lib/grape/endpoint.rb, lib/grape/validations/params_scope.rb, spec/grape/validations_spec.rb
Now, route settings get declared params when an endpoint gets initialized, the `Grape::Validations::ParamsScope` doesn't need to worry about that anymore.
Since the endpoint takes care of finalizing declared params, the `declared_params` method works with a structure which doesn't require any processing.
=> Simplify logic for defining declared params

CHANGELOG.md, lib/grape/api/instance.rb, lib/grape/router.rb, spec/grape/api_spec.rb
Noticed that calling the `route` method in a `before` hook causes an `NoMethodError` when the hook is invoked for the automatically generated Method Not Allowed endpoints. The reason seems to be that the route information dictionary is not populated in these cases.
These changes will populate the route information before calling the method not allowed endpoint. Also included some minor refactoring for the methods involved in all this.
=> Populate the env route information when calling the automatically added endpoints

CHANGELOG.md, lib/grape/router.rb
I recently updated one of our apps from grape 1.2.5 to 1.3.3 and have observed a memory leak. After analysing some heap dumps taken from our app I believe I have tracked this back to part of the changes in #2002 
The change to router.rb caches normalized paths here: https://github.com/ruby-grape/grape/blob/master/lib/grape/router.rb#L10
This retains indefinitely every path that flows through grape. We have a number of apis where the path is of the form `foo/bar/id/action` where id is the id of the object the api call is acting on, so this grows in a more or less unbounded way.
Since this was just a memory optimization, I would suggest just reverting that part of the changes in #2002 which is what this PR does
=> Fix memory leak caused by caching all unique paths seen

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb
The pull request #1520 introduced a regression that always caused the
`Cache-Control` HTTP header to be set to `no-cache`, even if the
response wasn't a stream. To fix this, we only set HTTP headers if there
is an actual stream.
Closes https://github.com/ruby-grape/grape/issues/2087
=> Set Cache-Control only for streamed responses

CHANGELOG.md, README.md
=> Update README to fix 404 error issue mounting Grape Using Rack::Cascade

CHANGELOG.md, README.md
Correct an example params in `Include Missing` doc.
=> Improve include missing doc

CHANGELOG.md, lib/grape/api.rb, lib/grape/dsl/routing.rb, lib/grape/middleware/base.rb, lib/grape/middleware/error.rb, lib/grape/middleware/stack.rb, lib/grape/request.rb, lib/grape/router.rb, lib/grape/router/attribute_translator.rb, lib/grape/util/base_inheritable.rb, lib/grape/validations/validators/as.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/default.rb, lib/grape/validations/validators/except_values.rb, lib/grape/validations/validators/values.rb, spec/grape/middleware/error_spec.rb, spec/grape/middleware/stack_spec.rb, spec/support/versioned_helpers.rb
Another attempt to address https://github.com/ruby-grape/grape/issues/2090 properly
=> Fix Ruby 2.7 keyword deprecations

CHANGELOG.md, lib/grape/validations/validators/default.rb, spec/grape/validations/validators/default_spec.rb
Hello,
`Grape::Validations::Base#validate!` calls `#validate_param!` only if `@scope.meets_dependency?(val, params)` is truthy.
But `Grape::Validations::DefaultValidator#validate!` ignores the cope dependency now.
It doesn't matter in most cases because of `@scope.should_validate?`, but this is not the case for an array that contains both matching and non-matching conditions.
So I guess `Grape::Validations::DefaultValidator#validate!` should the check scope dependency as same as `Grape::Validations::Base#validate!`.
How about it?
=> Skip to set default value unless `meets_dependency?`

CHANGELOG.md, Gemfile, benchmark/remounting.rb, lib/grape/api.rb, spec/grape/api_spec.rb
This is a simple fix for #2071. 
`Grape::API` class methods that are not referenced in the `NON_OVERRIDABLE` constant are overridden to call `add_setup` when invoked. Unfortunately there is a memory leak with `add_setup` where a hash describing the class method call is added to `@setup` on every call (not just the first). This PR changes the data structure of `@setup` from an `Array` to a `Set` therefore only allowing a single hash per combination of method name and arguments.
This bug is causing pain for us as we call `Grape::API.logger` in every API request 📈 In our case `Grape::API.logger` with no arguments is sorted by moving to a `Set`, but I am not too familiar with the inner workings of Grape so I will ask for some guidance of whether this doesn't meet a particular edge case or …
=> Fix retaining setup blocks when remounting APIs

Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack1.gemfile, gemfiles/rack2.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile, gemfiles/rails_edge.gemfile
The latest versions of rubocop-ast (>= 0.7) are incompatible with older versions of rubocop. Since grape currently use rubocop 0.84 we need to lock rubocop-ast to a compatible version
=> Lock rubocop-ast to < 0.7

lib/grape/dsl/inside_route.rb, spec/grape/endpoint/declared_spec.rb
Fixes an issue introduced in 7e432153f08d4985b0df625d11aef28a38beb4fe that results in Array leaf params being ignored.
For example, given the following API and Request:
```
class Api < Grape::API
params do
optional :array, type: Array
end
post 'example' do
declared(params, include_missing: true)
end
end
POST /example
{ "array": ["value"] }
```
Expected Response Body:
```
{ "array": ["value"] }
```
Observed Response Body:
```
{ "array": [] }
```
=> Fix bug with handling array params.

CHANGELOG.md, lib/grape/dsl/inside_route.rb
This fixes the warning:
```
ruby/2.7.0/gems/grape-1.4.0/lib/grape/dsl/inside_route.rb: warning:
Using the last argument as keyword parameters is deprecated; maybe **
should be added to the call
```
More details:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
=> Fix Ruby 2.7 deprecation warning

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint/declared_spec.rb
Prior to Grape v1.5.0 and https://github.com/ruby-grape/grape/pull/2103, the following
would return `nil`:
```ruby
params do
optional :status_code, types: [Integer, String]
end
get '/' do
declared_params
end
```
However, now it turns an empty `Array`.
We restore the previous behavior by not returning an empty `Array` if multiple
types are used.
Closes https://github.com/ruby-grape/grape/issues/2115
=> Fix declared_params regression with multiple allowed types

CHANGELOG.md, lib/grape/middleware/stack.rb
Attempt at fixing #2122 
See https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ (`Handling argument delegation`)
=> Fix 2.7 deprecation warning in middleware/stack

CHANGELOG.md, lib/grape/validations/validator_factory.rb
Addresses the following warnings:
```
/app/vendor/bundle/ruby/2.7.0/gems/grape-1.5.0/lib/grape/validations/validator_factory.rb:7: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/app/vendor/bundle/ruby/2.7.0/gems/grape-1.5.0/lib/grape/validations/validators/values.rb:6: warning: The called method `initialize' is defined here
```
=> Fix 2.7 deprecation warning in validator_factory

CHANGELOG.md, lib/grape/router/attribute_translator.rb
This fixes warnings about redefined attribute readers for `AttributeTranslator#requirements` and `#request_method`. The `attr_reader` call is redundant because those accessors are defined dynamically below that.
```
/Users/samsonjs/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/grape-1.5.0/lib/grape/router/attribute_translator.rb:31: warning: method redefined; discarding old requirements
/Users/samsonjs/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/grape-1.5.0/lib/grape/router/attribute_translator.rb:31: warning: method redefined; discarding old request_method
```
=> Fix warnings about redefined methods on AttributeTranslator

CHANGELOG.md, UPGRADING.md, lib/grape/validations/params_scope.rb
Fixes https://github.com/ruby-grape/grape/issues/2100
The reason was in `ActiveSupport::HashWithIndifferentAccess`, it is super expensive.
When users use a `Grape::Extensions::ActiveSupport::HashWithIndifferentAccess::ParamBuilder` or `Grape::Extensions::Hashie::Mash::ParamBuilder` parameter builder there is no change. However, users who use `Grape::Extensions::Hash::ParamBuilder` must make sure a parameter to be dependent on must be a symbol.
```ruby
given :matrix do
end
```
Benchmark after this fix:
```
Warming up --------------------------------------
Given     1.000  i/100ms
Simple     1.000  i/100ms
Calculating -------------------------------------
Given      0.804  (± 0.0%) i/s -     49.000  in  61.186831s
Simple      0.855  (± 0.0%) i/s -     52.000  in  60.926097s
Comparison: …
```
=> fix a performance issue with dependent params

CHANGELOG.md, lib/grape/dsl/parameters.rb, lib/grape/validations/single_attribute_iterator.rb, lib/grape/validations/validators/base.rb, spec/grape/validations/single_attribute_iterator_spec.rb, spec/grape/validations_spec.rb
This bug is due to the params parsing code return `{}` when the value is not found.
This is fine in most cases, however in the instance that the value was optional
and has nested required values.
I was not able to find a way to confine the changes to just the parameter parsing
as this resulted in the indexing being incorrect if any of the other array objects
had an error.
I have used a class to indicate that an Optional Value was missing as this avoid issues
with the value actually being in the response.
=> Fix validation error for nested array when  `requires` => `optional` => `requires`

CHANGELOG.md, lib/grape/validations/attributes_iterator.rb, lib/grape/validations/multiple_attributes_iterator.rb, lib/grape/validations/single_attribute_iterator.rb, lib/grape/validations/validators/multiple_params_base.rb, spec/grape/validations/multiple_attributes_iterator_spec.rb, spec/grape/validations_spec.rb
These have previously been fixed for the Base class for validators that only work with a single parameter.
=> Fix incorrect optional validation issues for MultipleParamsBase

CHANGELOG.md, lib/grape/validations/validators/coerce.rb
Fix these deprecation warnings
```
grape/lib/grape/validations/validators/coerce.rb:21: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
grape/lib/grape/validations/validators/base.rb:16: warning: The called method `initialize' is defined here
```
=> Fix Ruby 2.7 keyword deprecation warning in validators/coerce

CHANGELOG.md
the changelog for Grape 1.5.0 has an entry that was pointing to the wrong PR.
=> fix PR reference in changelog

CHANGELOG.md, lib/grape/middleware/stack.rb, spec/grape/middleware/stack_spec.rb
* See https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/#a-compatible-delegation
More context on https://github.com/ruby-grape/grape/pull/2123#issuecomment-728384065
This also happens to fix the CI on `truffleruby-head`.
=> Use #ruby2_keywords for correct delegation on Ruby <= 2.6, 2.7 and 3

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/api_remount_spec.rb
=> fixes configuration inside namespaced params scope

CHANGELOG.md, Gemfile, README.md, lib/grape/validations/types.rb, lib/grape/validations/types/custom_type_coercer.rb, lib/grape/validations/types/invalid_value.rb, lib/grape/validations/validators/coerce.rb, spec/grape/validations/validators/coerce_spec.rb
Just return an instance of `Grape::Types::InvalidValue` with the message:
```ruby
class Color
def self.parse(value)
return value if %w[blue red green].include?(value)
Grape::Types::InvalidValue.new('Invalid color')
end
end
```
Any raised exception will be treated as an invalid value as it was before.
Implements an idea listed in https://github.com/ruby-grape/grape/issues/2093
=> Custom types can set a message to be used in the response when invalid

.github/workflows/test.yml
Rails 7 is dropping pre Ruby 2.7 support. So limiting the Rails edge tests to only be executed on 2.7
=> Fix testing to be compatible with Rails 7 dependencies

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
**- What is it good for**
There is a nasty bug on edge case usage of nested mounted APIs which use a shared class-helper method to abstract the creation of a route. With this fix in place, no errors are raised. Otherwise a `RuntimeError: can't add a new key into hash during iteration` is raised. This is caused by [an inline modification of the @setup set inside the Grape::API class](https://github.com/ruby-grape/grape/blob/v1.5.2/lib/grape/api.rb#L144). This error is caused by the definition of the helper method in a specific way. The following form causes the issue:
```ruby
def uniqe_id_route
params do
use :unique_id
end
route_param(:id) do
yield
end
end  
```
while this form works as expected:
```ruby
def uniqe_id_route(&block)
params do
use :unique_id
end
route_param(:id, &block)
end …
```
=> Corrected a hash modification while iterating issue.

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/validations/types/custom_type_coercer.rb, spec/grape/validations/validators/coerce_spec.rb
Regarding the expected behavior pointed by @dblock 
> So should we adjust the default validator behavior ?
Yes, I believe so. A `nil` value is a `nil` value, not the absence of a parameter.
_Originally posted by @dblock in https://github.com/ruby-grape/grape/issues/2040#issuecomment-615868085_
Here is a first attemp to fix the behavior applied to the CustomTypeCoercer
=> coerce_with should be called for params with nil value

lib/grape/endpoint.rb, lib/grape/parser/json.rb, lib/grape/parser/xml.rb, lib/grape/request.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/multiple_params_base.rb
This avoids using the `Kernel#raise` string message parameter to initialize custom data for errors in favor of initializing with the data directly as described here:
https://github.com/ruby-grape/grape/pull/2164#issuecomment-791597922
This is also consistent with other usages like:
https://github.com/ruby-grape/grape/blob/e0f412ca73f6188c233ac9c35661027d28f38a54/lib/grape/middleware/versioner.rb#L29
https://github.com/ruby-grape/grape/blob/e0f412ca73f6188c233ac9c35661027d28f38a54/lib/grape/endpoint.rb#L129
=> Initialize error data using constructors directly

UPGRADING.md
I'm currently upgrading a fairly big rails app I did not write myself which uses grape. Since I unfortunately never used grape before (I want to though :wink:), I was in unknown territory and it took me quite I while to figure out that grape added support for rack >= 2.1.0 first on 1.3.0.
First thing I did when running into [https://github.com/ruby-grape/grape/issues/1966](this error) was checking the Upgrade.md file for any signs of rack incompatibility, but I did not find any. I wish I did, since it took me a few hours to find the mentioned issue. (I really have to up my google-fu, I know :see_no_evil:)
But for any poor soul in the future, who is just as bad as googling as I am, it might be helpful to mention this in the Upgrade guide :)
=> Mention rack 2.1.0 support in UPGRADING.md

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
Fixes #2094 where it was found that defining `as:` before `default:` would fail to add the default whereas `as:` after `default:` would work fine.
=> Fix ordering issues between as: and default: validations

.github/workflows/test.yml
This is a very small change, but which avoids a Float-to-String loss of characters.
You can see the effect of what it looks like before this change, in this picture:
Read more details, if you like: https://github.com/actions/runner/issues/849
=> CI: Avoid YAML float 3.0 => "3"

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
`API.make_inheritable` was overriding `.inherited` hook on given instance itself. But it was not calling `super` which is required to bubble up the inheritance chain.
This PR removes `.make_inheritable` and calls `super` instead.
Fixes PR with reproducible spec #2179.
=> Call `super` in `API.inherited`

CHANGELOG.md, lib/grape/middleware/base.rb, spec/grape/middleware/base_spec.rb
**- What is it good for**
When using the `Grape::Middleware::Base#response` method multiple times from within a custom middleware, the method generates a `Rack::Response` instance each (multiple) time.
[Do not convert Rack::Response to Rack::Response](https://github.com/ruby-grape/grape/commit/7ad647a873b666ad90ebd512c58d037db2f6148e) was missing the memoization I think, because [Don't create Grape::Request multiple times](https://github.com/ruby-grape/grape/commit/22b3aefda6ef31cda2379b3d80ab8299adddd27a#diff-0575f1465bc0e57934dfcda6d3c6b81846e771a1bfce6774b1302787a8e68468) already added memoization for `#request`.
**- What I did**
While writing a simple middleware that should append a response header I hit an unexpected behavior while using the `Grape::Middleware::Base#response` helper. …
=> Memoize the result of Grape::Middleware::Base#response.

CHANGELOG.md, spec/grape/api_spec.rb
**- What is it good for**
Fix the broken ruby-head continuous integration build ([latest master](https://github.com/ruby-grape/grape/runs/3790202051)). 
**- What I did**
Looks like ruby 3.1.0-dev adds a more verbose exception message with the raising line as a suffix. 
```ruby
pp e.message
"undefined method `not_exist_method'"
pp e.message
"undefined method `not_exist_method'\n" +
"\n" +
"          raise NoMethodError, \"undefined method `\#{handler}'\" unless respond_to?(handler)\n" +
"          ^^^^^"
```
So I just converted the `raise_error` message from a string to a regexp to ignore the new suffix.
**- A picture of a cute animal (not mandatory but encouraged)**
=> Fixed the broken ruby-head NoMethodError spec.

CHANGELOG.md, README.md, lib/grape/middleware/auth/dsl.rb, spec/grape/middleware/auth/dsl_spec.rb, spec/grape/middleware/auth/strategies_spec.rb
Rack Digest Auth [allows](https://github.com/rack/rack/blob/e0993d47096d36535dbe725091963a7e0f5aab52/lib/rack/auth/digest/md5.rb#L123) to check the user's credentials with ha1 digest hash instead of check with a plain password. But at the moment this functionality is not available because the condition from `Rack::Auth::Digest::MD5` is always false
```ruby
if opaque.nil? and realm.respond_to? :values_at
realm, opaque, @passwords_hashed = realm.values_at :realm, :opaque, :passwords_hashed
end
```
(in the grape auth dsl we constantly set the option `opaque` - `options[:opaque] ||= 'secret'`)
=> allow set passwords_hashed option for digest auth

lib/grape/dsl/headers.rb, spec/grape/dsl/headers_spec.rb
In an interview recently, I was given the Grape repository sans the
content of this method as a technical screening question. The task was
to discover what had been removed from the project and re-implement the
missing code using only the test suite.
It was actually fairly difficult to re-implement this method because
there are a couple of untested responsibilities. I think this is a
fairly integral component of the framework, so it makes sense to fully
test its functionality.
=> Expand test coverage of undocumented functionality

spec/grape/api_spec.rb
rely less on `Logger` internals (`Logger` on ruby-head has a different interface and slightly different format message)
I've simplified the spec by removing the log format expectation since that is not what we provide in Grape(not a Grape responsibility).
=> Fix spec for ruby-head

README.md
Hello.
https://github.com/ruby-grape/grape/pull/2200 changes `Grape::Validations::Base` into `Grape::Validations::Validators::Base`
The readme needs to be updated.
=> Update README.md (changes Grape::Validations::Base into Grape::Validations::Validators::Base)

lib/grape.rb, lib/grape/dsl/api.rb, lib/grape/dsl/callbacks.rb, lib/grape/dsl/configuration.rb, lib/grape/dsl/helpers.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/middleware.rb, lib/grape/dsl/parameters.rb, lib/grape/dsl/request_response.rb, lib/grape/dsl/routing.rb, lib/grape/dsl/settings.rb, lib/grape/dsl/validations.rb, lib/grape/middleware/auth/dsl.rb
Since `active_support/concern` is required more than once,  I thought it would be better to require it once instead of multiple times.
=> Move require 'active_support/concern' in grape.rb

CHANGELOG.md, benchmark/nested_params.rb, lib/grape/dsl/desc.rb, lib/grape/dsl/validations.rb, spec/grape/dsl/validations_spec.rb
While investigating another issue I discovered that params were documented twice then [merged there](https://github.com/ruby-grape/grape/blob/5053b797429279d91818e2116034ba40636338bb/lib/grape/dsl/routing.rb#L132-L134).
Params are stored in `namespace_stackable` there is no reason to keep them in `route_setting(:description)` too.
I checked this change against our app, it still works :wink:
=> do not collect params in route settings

CHANGELOG.md, lib/grape/error_formatter/json.rb, spec/grape/api_spec.rb
If we receive a request with an unsupported format, that user-provided format is included in the generated error message.  If the format includes non-UTF-8 characters and the app is configured to generate JSON error messages, a `JSON::GeneratorError` is raised.
To work around this error, this PR uses `String#encode`'s ability to replace invalid and undefined UTF-8 characters before calling `Grape::Json::dump`.
=> Remove non-UTF-8 characters from format before generating JSON error

CHANGELOG.md, lib/grape.rb, lib/grape/validations/validators/base.rb, spec/grape/api/custom_validations_spec.rb
=> fix a breaking change provided in 1.6.1

CHANGELOG.md, Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack1.gemfile, gemfiles/rack2.gemfile, gemfiles/rack2_2.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7.gemfile, gemfiles/rails_edge.gemfile, spec/grape/dsl/request_response_spec.rb, spec/grape/dsl/routing_spec.rb
Closes https://github.com/ruby-grape/grape/issues/2247.
See https://github.com/rspec/rspec-expectations/issues/1359#issuecomment-1053602543
=> Upgraded to rspec 3.11.0.

.github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md
GitHub CI doesn't have a feature to ignore certain steps in CI, so it looks like Grape build is continuously broken. This isn't the case. This PR extracts edge CI into a separate workflow that only runs on pull requests.
=> Split CI matrix, extract edge.

CHANGELOG.md, lib/grape.rb, lib/grape/exceptions/missing_group_type.rb, lib/grape/exceptions/unsupported_group_type.rb, spec/grape/exceptions/missing_group_type_spec.rb, spec/grape/exceptions/unsupported_group_type_spec.rb
Since #2227 there'a an alias for `MissingGroupTypeError` and `UnsupportedGroupTypeError` but there's no deprecation warnings. This PR adds the deprecation warnings inspired by #2244
=> Add deprecation warning for UnsupportedGroupTypeError And MissingGroupTypeError

README.md
As of 1.6+ Grape only allows you to use `declared(params)` when using `as` parameter for renaming parameters.
It's referenced in an issue: https://github.com/ruby-grape/grape/issues/2237 and also referenced [here](https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#upgrading-to--160).
Was confused for a bit until I found the issue - so thought it could help save some future folks (e.g. me!) time. Decided to remove the legacy way of accessing renamed parameters and suggest only using `declared(params)` moving forward.
=> 📝  Update `README.md` with `rename`-ing notes for `params`

README.md
This updates the documentation to raise instead of fail during custom validator exceptions as noted in #2188. The tests already use raise instead of fail as here so no change is needed there: https://github.com/ruby-grape/grape/blob/5cc3226a77a3dd294b26b0c09c2707c36d50cf99/spec/grape/validations_spec.rb#L1195
Closes #2188
=> Update documentation to use raise instead of fail for custom validation exception

.coveralls.yml, .github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md
Currently
```
Randomized with seed 1113
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Couldn't find a repository matching this job.
Coverage is at 98.94%.
Coverage report sent to Coveralls.
```
On my fork after adding the Coveralls token
```
Randomized with seed 57600
[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job ##8.1
[Coveralls] https://coveralls.io/jobs/101153293
Coverage is at 98.94%.
Coverage report sent to Coveralls.
```
- Reference a good comment: https://github.com/lemurheavy/coveralls-public/issues/1613#issuecomment-1028302521
- `coveralls-reborn` using `COVERALLS_REPO_TOKEN` https://github.com/tagliala/coveralls-ruby-reborn/blob/e17e7c4c7776fb2f74a225905d421f01382f3f2b/lib/coveralls/configuration.rb#L22
- The service name in …
=> Fix Coveralls code coverage

.coveralls.yml, .github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md, Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack1.gemfile, gemfiles/rack2.gemfile, gemfiles/rack2_2.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_6.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7.gemfile, gemfiles/rails_edge.gemfile, spec/spec_helper.rb
This uses the Coveralls GitHub Action in place of `coveralls-reborn` as recommended in the gem README https://github.com/tagliala/coveralls-ruby-reborn#github-actions and as discussed here https://github.com/ruby-grape/grape/pull/2265. The parallel test steps are taken from the Action README https://github.com/coverallsapp/github-action
Examples on my fork: 
- Job for a merge showing individual Ruby version & Gemfile matrix https://coveralls.io/builds/50032540
- Master after a merge https://coveralls.io/github/duffn/grape
=> Use Coveralls GitHub Action

CHANGELOG.md, lib/grape/validations/types/primitive_coercer.rb, spec/grape/validations/types/primitive_coercer_spec.rb
In 1.3+ if someone had a `Numeric` type parameter which worked in `<1.3` - any valid non-blank value will silently fail validation
```ruby
params { optional :price, type: Numeric }
```
This happens because dry-types does not contain built-in type for `DryTypes::SomeScope::Numeric` and `const_get` by default searches ancestors, thus finding `::Numeric`.
Runtime error ``undefined method `[]' for Numeric:Class`` is treated as a validation error and leads to unexpected behavior.
This PR adds mapping for Numeric that fixes it, also fallback to `const_get(.., false)` will make similar issues easier to debug.
=> Numeric is not a dry-types built-in type, fix coercion/validation

CHANGELOG.md, lib/grape/validations/types/primitive_coercer.rb, spec/grape/validations/types/primitive_coercer_spec.rb
This is a follow-up to https://github.com/ruby-grape/grape/pull/2271 - prevent silent validation fails for types not built-in in dry-types.
Instead of validation fail - check for `[]` method presence in provided class at init time.
=> Check for dry-types type existence and prevent unexpected top level const lookup

CHANGELOG.md, lib/grape/middleware/error.rb, spec/grape/middleware/error_spec.rb
support the ability to use the Rack::Utils's status_code symbols instead of integers.
=> Error middleware support using rack util's symbols as status

CHANGELOG.md, lib/grape/exceptions/base.rb, lib/grape/exceptions/validation.rb, spec/grape/exceptions/base_spec.rb
=> Fix exception super

CHANGELOG.md, lib/grape/middleware/error.rb, spec/grape/api_spec.rb
found an unexpected backtick while learning
=> An unexpected backtick

CHANGELOG.md, lib/grape/dsl/inside_route.rb, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
`evaluate_given` ignores tests for arrays, and it judges with the wrong parameters.
=> fix evaluate given in array

CHANGELOG.md, lib/grape/dsl/parameters.rb, spec/grape/validations_spec.rb
for backward compatibility with the previous implemention
where options param behaves as an empty hash by default
see #2295
=> fix, do not use kwargs for empty args 

CHANGELOG.md, grape.gemspec
Since the last #2302, we lost the `rack` minimal version that we had before `>= 1.3.0`. This PR is adding that minimal version.
=> Rack: Add >= 1.3.0 like before

lib/grape/exceptions/base.rb
It's better to call `super` as soon as possible as it is a parent :)
=> Grape::Exceptions::Base#initialize: call super earlier

CHANGELOG.md, lib/grape.rb, lib/grape/types/invalid_value.rb, lib/grape/validations/types/invalid_value.rb
This PR moves the `Grape::Types::InvalidValue` class definition into a separate file so that it can be lazy loaded in projects that use zeitwerk file structure conventions.
In environments that do not eager load, referencing the `Grape::Validations::Types::InvalidValue` class before `Grape::Types::InvalidValue` causes a load error due to the fact that both classes were defined in the same file.
---
**Testing?! Yes! Kind of...**
I haven't come up with a good way to write a _new_ rspec example for this change, but one test did fail on my branch before I updated `lib/grape.rb`. This failure occurred in [`coerce_spec.rb:271`](https://github.com/ruby-grape/grape/blob/master/spec/grape/validations/validators/coerce_spec.rb#L271) because …
=> Move convenience class into new file

README.md
Change in response to discussion in #2308: Added explanation on how to not set HTTP response bodies with status codes other than 204.
=> [skip ci] Add how to empty the body with status codes other than 204 

.gitignore, .yardopts, CHANGELOG.md, CONTRIBUTING.md, spec/grape/validations_spec.rb
This fixes the rendering of the YARD docs in markdown. RudyDoc reads `.yardopts` so this will work there too.
As one small example:
Before
After
=> Fix YARD docs markdown rendering

CHANGELOG.md, Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_1_0.gemfile, gemfiles/rack_2_0.gemfile, gemfiles/rack_3_0.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_5_2.gemfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, gemfiles/rails_edge.gemfile
This PR updates `rspec` to its latest version and relax its expected version to `< 4'
Fix #2314
=> Update rspec version from `3.11.0` to `< 4`

CHANGELOG.md, README.md, lib/grape/validations/params_scope.rb, spec/grape/validations/validators/values_spec.rb
allows using endless range for values validator.
e.g.
```ruby
params do
requires :minimum, type: Integer, values: 10..
optional :maximum, type: Integer, values: ..10 
end
```
=> fix using endless ranges for values parameter.

.github/workflows/edge.yml, CHANGELOG.md, README.md, spec/grape/validations/validators/values_spec.rb
In https://github.com/ruby-grape/grape/pull/2323 a real failure was drowed in edge failures. 
Changing the edge workflow to only run on demand, nobody is paying attention until someone says otherwise.
=> Make edge workflows only run on demand.

CHANGELOG.md, lib/grape.rb, lib/grape/validations/validators/base.rb
While looking at the Validator's registration process, I found that `convert_to_short_name` could be replaced by some ActiveSupport::Inflector methods like `demodulize`.
=> ActiveSupport inflector methods

CHANGELOG.md, lib/grape/endpoint.rb
This PR change the way validator are created before calling `validate`. `run_validators` has always created all the validators before calling `validate`. In a case where an exception is raised and the validator `fail_fast?` returns true, the remaining validators won't be `validate`. Thus, we can optimize the validation process by yielding validator instead of creating all of them at first. It's a small memory optimization and maybe it will speed up a little bit any endpoint that has a validator with `fail_fast`
In the same file, I also replaced some `|| []` by `&.`
=> run_validators memory optmization

CHANGELOG.md, lib/grape/validations/validators/values_validator.rb, spec/grape/validations/validators/values_spec.rb
This PR fixes the issue presented here: #2280
As this is my first contribution to the repo, I am open to any form of feedback!
PS: I also created the tests with the example shown in the issue in mind.
=> Feature: Allows procs with arity 1 to validate and use custom messages 

CHANGELOG.md, lib/grape/validations/validators/base.rb, spec/grape/validations/validators/base_spec.rb
=> Fix custom validator not ending with _validator

CHANGELOG.md, lib/grape/validations/multiple_attributes_iterator.rb, lib/grape/validations/single_attribute_iterator.rb, lib/grape/validations/validators/base.rb, lib/grape/validations/validators/multiple_params_base.rb, spec/grape/validations/multiple_attributes_iterator_spec.rb, spec/grape/validations/single_attribute_iterator_spec.rb
This PR will stop yielding `skip` value since iterators are already ignoring `skip` values.
Resolves #2329
=> Stop yielding skip value

.github/workflows/test.yml, Appraisals, CHANGELOG.md, grape.gemspec, spec/grape/endpoint_spec.rb, spec/grape/middleware/formatter_spec.rb
As suggested in https://github.com/ruby-grape/grape/issues/2298, here's a PR that adjusts test expectations to conform to rack 3
=> Adjust test expectations to conform to rack 3

.rubocop_todo.yml, CHANGELOG.md, grape.gemspec
It occurred to me while installing the gem that spec files are included. It represents half the size of the gem. Nowadays, most  gem does not include them and I think Grape should do the same.
=> Reduce gem size by removing test_files (spec)

CHANGELOG.md, README.md, lib/grape/middleware/formatter.rb, spec/grape/middleware/formatter_spec.rb
This PR ensures that Accept headers with mime types without a given quality value, are parsed as having a quality value of `1.0`.
The current value for mime types without a quality value is 0.0 (`nil.to_f`).
From the HTTP specification (RFC 9110), https://www.rfc-editor.org/rfc/rfc9110.html#name-accept and https://www.rfc-editor.org/rfc/rfc9110.html#name-quality-values:
> The weight is normalized to a real number in the range 0 through 1, where 0.001 is the least preferred and 1 is the most preferred; a value of 0 means "not acceptable". If no "q" parameter is present, the default weight is 1.
=> Quality arguments to `Accept` header should default to 1.0

CHANGELOG.md, lib/grape/endpoint.rb, spec/grape/endpoint_spec.rb
Hi all! 👋 
My first contribution to the Grape project. Let's see if this can help to solve the issue #2236 
With the fix, when referencing an undefined local variable within a grape controller, Grape is returning this error message.
(error trace updated after applying @dblock suggestions)
```shell
NoMethodError: undefined method `authenticate!' for #<Class:0x0000000103996728> in `/foo' endpoint
/Users/Juancarlos.Garcia/code/grape/lib/grape/endpoint.rb:408:in `method_missing'
/Users/Juancarlos.Garcia/code/grape-2236/api.rb:7:in `block in <class:MyAPI>'
/Users/Juancarlos.Garcia/code/grape/lib/grape/endpoint.rb:58:in `call'
/Users/Juancarlos.Garcia/code/grape/lib/grape/endpoint.rb:58:in `block (2 levels) in generate_api_method'
/Users/Juancarlos.Garcia/.rvm/gems/ruby-3.2.2/gems/activesupport- …
```
=> fix(#2236): Stripping the internals of `Grape::Endpoint` when `NoMethodError` is raised

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint/declared_spec.rb
Hi 👋 
I was taking a look to the issue #2195 .
Seems the error is because the logic inside the `handle_passed_param` method is using the `start_with?(key)` method. So, if we have two params like `:empty_hash` and `:empty_hash_two`, as both of them share part of the key, it detects that the `:empty_hash` parameter has children, and it behaves in a different way and it ends returning a `nil` value.
For solving it, I'm checking that for having children the key of the children should start with the same key name + a `[`. Maybe not the better solution for checking this 🤔 so open to discussion.
=> fix(#2195): Fix `declared` method for hash params with overlapping names

CHANGELOG.md, README.md, UPGRADING.md
From a conversation with @dblock in https://github.com/ruby-grape/grape/pull/2371#discussion_r1398210065 I've manually fixed the markdown files for following 1-line format.
I've tried to add the [rubocop-md](https://github.com/rubocop/rubocop-md) gem, so it can be detected in future PRs. However, there is not a specific rule for this purpose.
An alternative would be add this validation to your https://github.com/ruby-grape/danger project. 
What do you think? Do you think is interesting to merge this "fix"?
=> fix: Updating markdown files for following one-line format

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/router/route.rb, lib/grape/version.rb, spec/grape/api_spec.rb
While profiling #2363, I found that `to_ary` is leaking as `Allocated String Report`.
It has been fixed in by #466 but lost since.
=> method missing to_ary

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, lib/grape/middleware/error.rb, spec/grape/api_spec.rb
Hey 👋 
I was taking a look at #1922 and after some checks I can see that we are in a different instance when we are inside the `rescue_from` method.
```ruby
require 'grape'
class MyAPI < Grape::API
class MyError < StandardError; end
before do
puts "self => #{self.class}"
@my_var = 328
end
rescue_from MyError do |e|
puts "self => #{self.class}"
puts "my var value => #{@my_var}"
error!({ my_var: @my_var }, 401)
end
get '/wadus' do
puts "my var value => #{@my_var}"
puts "self => #{self.class}"
raise MyError.new
end
end
```
The current output of the previous code is:
```shell
self =>#<Class:0x0000000107c79d88>
my var value => 328
self => #<Class:0x0000000107c79d88>
self => ##<Class:0x0000000104c77950>
my var value =>
```
This means that we cannot have access to the same instance variables …
=> fix(#1922): Allow to use instance variables defined in the endpoints inside rescue_from

CHANGELOG.md, README.md, UPGRADING.md, grape.gemspec, lib/grape/router/pattern.rb, spec/grape/api/recognize_path_spec.rb, spec/grape/api_spec.rb
Hey 👋 
This PR tries to fix the issue described in #2350
With this changes, the `recognize_paths` method takes into account the `route_param` type (if specified) for determine if a path matches with the performed request.
This change has an important implication that has been added to the `UPGRADED` file:
Before this change, if a request was performed to an endpoint that has specified the type of the `route_param`, the path was recognized. If finally the provided parameter in the request didn't match with the specified `route_param` type. A `400 Bad Request` response was returning, indicating that the provided param in the path was not valid. With these changes, as the path is directly not recognized if it does not accomplish with the specified `route_param` type, we are returning a `404 …
=> fix(#2350): Update `recognize_paths` taking into account the `route_param` type

CHANGELOG.md, lib/grape/router.rb
Since ruby 2.6, the Regex's `match` function comes with a [block](https://ruby-doc.org/core-2.6/Regexp.html#method-i-match) that will be executed only if match succeed. This PR is just a small refactor
=> Use regex block instead of if

.rubocop_todo.yml, CHANGELOG.md, README.md, lib/grape/api.rb, lib/grape/dsl/routing.rb, spec/grape/api/mount_and_helpers_order_spec.rb, spec/grape/api/mount_and_rescue_from_spec.rb
This PR tries to "fix" the issue described in #1975 .
Right now, as we can read in our README, declarations as `before/after/rescue_from` must be placed before `mount` in a case where they should be inherited. 
However, I think this behavior arises from the existing implementation rather than being an intentional design. This occurs because when the `mount` method is invoked, a new `Endpoint` instance is generated, inheriting the previously registered `before/after/rescue_from` methods. However, if additional `before/after/rescue_from` methods are executed after the `mount` operation, the mounted endpoints remain unrefreshed.
Considering that:
1. Whenever a method is run within a `Grape::API` class, it is stored in the `@setup` variable in the sequence in which it was executed.
2. Upon …
=> fix(#1975): Allow to use `before/after/rescue_from` methods in any order when using `mount`

.github/workflows/danger.yml, .github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md
[rubygems-update 3.5.0](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#350--2023-12-15) dropped support for ruby 2.6 and 2.7. This PR sets `rubygems` to its default version for the following workflows:
- danger
-  test
Also, this PR keeps rubygems to its latest version and sets `ruby-version` to 3.2 for `rubocop`
=> Use rubygems default instead of latest

CHANGELOG.md, lib/grape/router/attribute_translator.rb, spec/grape/router/attribute_translator_spec.rb
This was simply not working before. Doesn't seem like there are any unit tests for this class, so I haven't added new ones, but might be worth considering.
=> Fix attribute translator setter

CHANGELOG.md, lib/grape/dsl/desc.rb, lib/grape/endpoint.rb, lib/grape/router.rb, lib/grape/router/attribute_translator.rb, lib/grape/router/greedy_route.rb, lib/grape/router/pattern.rb, lib/grape/router/route.rb, spec/grape/api_spec.rb, spec/grape/router/attribute_translator_spec.rb, spec/grape/router/greedy_route_spec.rb, spec/integration/rack/v2/headers_spec.rb
After #2375, I've spent some time understanding the `Grape::Router::AttributeTranslator` across the gem. I knew already what it did but I didn't know where it was used exactly. This PR is an effort to optimize the usage of the AttributeTranslator but also some refactoring across the `Grape::Router` classes.
Changes:
- Introducing `Grape::Router::GreedyRoute` to encapsulate `Grape::Router::AttributeTranslator` in the greedy match process.
- `Grape::Router::AttributeTranslator` defines more methods to not rely on `method_missing` internally.
- `Grape::Router::Pattern` and `Grape::Router::Route` have been refactored.
=> Optimize AttributeTranslator

CHANGELOG.md, docker-compose.yml, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb, spec/grape/endpoint_spec.rb, spec/grape/validations/params_scope_spec.rb, spec/grape/validations/validators/values_spec.rb, spec/integration/multi_xml/xml_spec.rb, spec/spec_helper.rb
This PR will set Grape::Deprecator's Behavior to `raise` when running specs. Our spec suite should not pass through our own deprecations unless its expected.
=> Change Grape::Deprecator's Behavior in test

CHANGELOG.md, Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_1_0.gemfile, gemfiles/rack_2_0.gemfile, gemfiles/rack_3_0.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, gemfiles/rails_7_1.gemfile, gemfiles/rails_edge.gemfile, spec/grape/api_spec.rb
This PR removes `mime-types` has a dependency when testing. It was only used in 3 specs.
=> Remove mime-types dependency in specs

.github/workflows/edge.yml, CHANGELOG.md, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb, spec/grape/entity_spec.rb, spec/grape/middleware/base_spec.rb, spec/support/basic_auth_encode_helpers.rb, spec/support/chunked_response.rb
=> Fix Rails Edge ruby 3.1

.rspec, CHANGELOG.md, lib/grape/router/greedy_route.rb, lib/grape/router/route.rb
Fix #2407. Also, it activates warnings in rspec
=> Fix params method redefined warnings

README.md
Since commit https://github.com/ruby-grape/grape/commit/11576c8b97d33439a555c7bd0f9146916874dc20, the built in `Grape::Formatter::Xml` does no longer fall back to calling the object's `#to_s` method if it does not respond to `#to_xml`. This pull request updates the documentation to match the behavior of the current version.
=> Remove outdated XML formatter documentation

README.md
This PR removes some old documentation related to old Rails versions.
=> Remove old Rails <= 5.2 documentation

CHANGELOG.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, lib/grape/middleware/error.rb, spec/grape/api_spec.rb, spec/grape/exceptions/body_parse_errors_spec.rb, spec/grape/exceptions/invalid_accept_header_spec.rb, spec/grape/validations/validators/values_spec.rb
Fix #2411 
Changes:
- Use `Rack::Utils.escape_html` instead of `ERB::Util.escape_html`
- Some refactor in error middleware.
- Remove `rack_response` from `inside_route`
- Remove some irrelevant `if: ActiveSupport::VERSION::MAJOR >= ?` in specs
=> Fix response headers from lint

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/extensions/hash.rb, spec/grape/extensions/param_builders/hash_spec.rb, spec/grape/extensions/param_builders/hash_with_indifferent_access_spec.rb, spec/grape/extensions/param_builders/hashie/mash_spec.rb
https://github.com/ruby-grape/grape/pull/2326 changed the behavior of params merging. Before v1.8.0 the following route:
```ruby
resources :users do
route_param :id do
get do
user = User.find(params[:id])
{ id: user.id }
end
end
end
```
would return `{ id: 12345 }` if called as
```
GET /users/12345?id=1
```
Now, since v1.8.0, it returns `{ id: 1 }` as `id` passed in params overwrites `route_param`.
This PR restores the previous behavior.
=> Do not overwrite route_param with a regular one if they share same name

CHANGELOG.md, Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/no_dry_validation.gemfile, gemfiles/rack_2_0.gemfile, gemfiles/rack_3_0.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, gemfiles/rails_7_1.gemfile, gemfiles/rails_edge.gemfile, spec/grape/entity_spec.rb
I thought it would be great to use the same JSONP gem in our test suite like we recommend in our README.
=> Use `rack-contrib` JSONP instead of rack-jsonp

CHANGELOG.md, lib/grape/dsl/headers.rb, lib/grape/endpoint.rb, lib/grape/request.rb, lib/grape/util/header.rb, spec/grape/api/custom_validations_spec.rb, spec/grape/dsl/headers_spec.rb, spec/grape/endpoint_spec.rb, spec/grape/request_spec.rb
This closes https://github.com/ruby-grape/grape/issues/2396
=> Replace Hash with Rack::Header/Rack::Utils::HeaderHash for Grape Headers

.github/workflows/test.yml
@dgutov do you think this is better? It gets rid of the indirections by removing the concept of "integration", and making both gemfile used and specs declarative.
=> DRY-up test workflow.

CHANGELOG.md, README.md, UPGRADING.md, lib/grape/dsl/parameters.rb, spec/grape/dsl/parameters_spec.rb
This PR changes the way attributes are merged for parameters within the Grape DSL by adopting a `deep_merge' strategy. This enhancement ensures that nested attributes specified at both the group and parameter level are fully merged, increasing flexibility and configuration precision in API definitions.
In the current implementation, specifying nested attributes at the parameter level completely overrides those set at the group level. This behavior can lead to unintended loss of configuration detail, especially in complex API setups where nuanced customizations are required across different parameters.
When using Grape's parameter grouping with the `with` method, any specific attributes defined at the parameter level will completely override the more generic attributes defined at the group …
=> Deep Merge for group parameter attributes

.github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md
I noticed these [warnings](https://github.com/ruby-grape/grape/actions/runs/8951965020) when running test workflow.
[coverallsapp/github-action](https://github.com/coverallsapp/github-action) changed `master` to `main`.
=> Fix nodejs16 within coverallsapp/github-action

CHANGELOG.md, README.md, lib/grape/dsl/parameters.rb, lib/grape/validations/params_scope.rb, spec/grape/dsl/parameters_spec.rb, spec/grape/validations/params_scope_spec.rb
Previously, the `with`' method in the Parameter DSL did not support nested structures. This forced to redefine the entire attribute set for each nested scope, which was cumbersome and prone to errors, especially in complex parameter structures.
This PR introduces enhanced functionality to the `with` method that allows nested scopes to inherit and extend the attributes defined in parent scopes. By merging attributes from the current group with the new attributes, it simplifies parameter declarations and ensures a clean, DRY approach to specifying shared attributes in nested parameter contexts.
=> Implement nested `with` support in parameter DSL

CHANGELOG.md, README.md, lib/grape/locale/en.yml, lib/grape/validations/attributes_doc.rb, lib/grape/validations/validators/length_validator.rb, spec/grape/validations/attributes_doc_spec.rb, spec/grape/validations/validators/length_spec.rb
This validator validates that the length of the parameter (if the parameter supports `#length` is within the specified limits).
I've also added the `min_length` and `max_length` limits to the attribute documentation so that they can be used to specify the limits for an array type in swagger.
=> Add length validator

spec/integration/rack_3_0/headers_spec.rb, spec/integration/rack_3_0/version_spec.rb
A followup for https://github.com/ruby-grape/grape/pull/2431.
=> Added Rack version specs to ensure the correct version is loaded.

CHANGELOG.md, lib/grape/endpoint.rb, spec/grape/endpoint_spec.rb
=> Replace method_missing by an overrided inspect

CHANGELOG.md, Gemfile, UPGRADING.md, grape.gemspec
=> Remove builder as a dependency

.github/workflows/test.yml, CHANGELOG.md, gemfiles/rack_3_1.gemfile, lib/grape/dsl/inside_route.rb, lib/grape/http/headers.rb, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb, spec/grape/middleware/formatter_spec.rb, spec/support/chunked_response.rb
I was about to make a release and [Rack 3.1](https://github.com/rack/rack/blob/v3.1.0/CHANGELOG.md) got released and a few specs were failing. I took to opportunity fix the them and add a proper rack_3_1_gemfile.
=> Rack 3.1 fixes

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/api_spec.rb
=> Add context in endpoint dsl

.github/workflows/test.yml, CHANGELOG.md, docker/Dockerfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, gemfiles/rails_7_1.gemfile, gemfiles/rails_edge.gemfile, lib/grape/router.rb, spec/integration/rails/mounting_spec.rb, spec/integration/rails/railtie_spec.rb
=> Fix default response headers to work with Rack 3

.simplecov, CHANGELOG.md, Gemfile, spec/spec_helper.rb
Fix #2466
Also, `lcov` format will be used only when running GH Actions.
=> Fix repo coverage

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/api_spec.rb
This pull request fix a compatibility issue with the `error!` method when used in `rescue_from` block.
Previously, the `rescue_from` block ran in context of `Grape::Middleware::Error`, where `error!` method had one signature. Now, block run in context of `Grape::DSL::InsideRoute`, where `error!` method has different signature. This change cause runtime errors when `error!` method was called with extra arguments like `backtrace` and `original_exception`.
This update make `error!` method signatures same across different contexts. By aligning these signatures, `error!` method can handle additional arguments consistently and preventing errors.
=> Align `error!` method signatures across different places.

.rubocop.yml, CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/endpoint/declared_spec.rb
Should fix the #2347 issue.
This pull request fixes an issue where the full_path method would stop building the full path when encountering lateral scopes like `with` or `given`. The updated method now correctly handles these cases, ensuring accurate path construction
Thanks @seriousdev-gh  for the [spec](https://github.com/ruby-grape/grape/pull/2462).
=> Fixes #2347 - Correct full path building for lateral scopes

CHANGELOG.md, lib/grape/error_formatter/json.rb, spec/grape/api_spec.rb
If the structure of the resulting error message does not lend itself to adding the original exception and custom backtrace, it should be skipped.
Fixes the #2472
=> Fix rescue_from ValidationErrors exception

CHANGELOG.md, UPGRADING.md, lib/grape/validations/validators/length_validator.rb, spec/grape/validations/validators/length_spec.rb
Thanks to @dhruvCW for adding the length validator(#2437).
I found that in the case of optional parameters, passing in nil will lead to an exception. This behavior is not very friendly.
For nil, it should be a better choice to skip verification directly.
=> The `length` validator only takes effect for parameters with types that support `#length` method

.rubocop_todo.yml, CHANGELOG.md, grape.gemspec
=> Adds rubygems_mfa_required to gemspec

docker/Dockerfile, docker/entrypoint.sh
I've added jemalloc in the Dockerfile + passing ruby options `yjit` and `frozen_string_literal`. Also, entrypoint will now execute de command with PID 1.
=> Some tweaks in Dockerfile

CHANGELOG.md, lib/grape/endpoint.rb, spec/grape/endpoint_spec.rb
=> Fix Grape::Endpoint's inspect method when not called in the context of an API

CHANGELOG.md, lib/grape/dsl/helpers.rb, lib/grape/endpoint.rb, lib/grape/middleware/error.rb, spec/grape/extensions/param_builders/hash_spec.rb, spec/grape/extensions/param_builders/hash_with_indifferent_access_spec.rb, spec/integration/hashie/hashie_spec.rb
This PR reduces object allocation when compiling an api.
The function `prepare_path` was calling `inheritable_setting.to_hash` 2 times to just keep `namespace_stackable` and `namespace_inheritable`.
```
Total allocated: 62277446 bytes (334535 objects)
Total retained:  5954533 bytes (15516 objects)
```
```
allocated objects by class
-----------------------------------
218676  Array
89913  Hash
```
```
Total allocated: 51007518 bytes (220812 objects)
Total retained:  5954325 bytes (15514 objects)
```
```
allocated objects by class
-----------------------------------
128512  Array
66354  Hash
```
This PR also changes the following
- use `include` instead of `.send(:include)`
- create a helpers module only if a helper is defined otherwise it's nil
- Remove `|| {}` in favor of handling `nil` …
=> Reduce object allocation while compiling

CHANGELOG.md, Gemfile, grape.gemspec
This PR updates the following gems.
- rubocop 1.66.1
- rubocop-performance 1.21.1
- rubocop-rspec 3.0.5
This PR also changes `add_runtime_dependency` to `add_dependency` [Gemspec/AddRuntimeDependency](https://rubydoc.info/gems/rubocop/RuboCop/Cop/Gemspec/AddRuntimeDependency)
=> Update rubocop to latest

CHANGELOG.md, UPGRADING.md, lib/grape/dsl/inside_route.rb, spec/grape/dsl/inside_route_spec.rb
This PR removes the deprecated `file` method.
=> Remove file method

CHANGELOG.md, UPGRADING.md, lib/grape/validations/validators/values_validator.rb
This PR removes the option `proc` and `except` in the values validator. It's been deprecated since version [1.0.0](https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#the-except-except_message-and-proc-options-of-the-values-validator-are-deprecated)
=> Remove deprecated except and proc in values validator

CHANGELOG.md, UPGRADING.md, lib/grape/dsl/desc.rb, spec/grape/dsl/desc_spec.rb
This PR will remove the deprecation message when `options` and `block` are used simultaneously when describing an API through the DSL function `desc`.
=> Remove deprecation msg + small refactor

CHANGELOG.md, lib/grape/validations/params_scope.rb, spec/grape/validations/params_scope_spec.rb
Not sure if this wants a change log as it feels more like a bug fix.
=> Fix Set type with values

CHANGELOG.md, lib/grape/validations/contract_scope.rb, spec/integration/dry_validation/dry_validation_spec.rb
I recently came across the ContactScope's validator. Like other validators, it should inherits from `Grape::Validations::Validators::Base`. This PR fix that and refactor a small part when building error messages
=> Fix ContractScope validator + small tweaks

CHANGELOG.md, benchmark/compile_many_routes.rb, lib/grape/endpoint.rb, lib/grape/path.rb, lib/grape/router/pattern.rb, lib/grape/router/route.rb, spec/grape/path_spec.rb
This PR refactors the usage of Grape::Path and it comes with a lower Hash allocation. Most of the changes are in `Grape::Path` and the `to_routes` function in `Grape::Endpoint`
This is the result taken from the `benchmark/compile_many_routes.rb`
```ruby
require 'memory_profiler'
class API < Grape::API
prefix :api
version 'v1', using: :path
2000.times do |index|
get "/test#{index}/" do
'hello'
end
end
end
MemoryProfiler.report(allow_files: 'grape') do
API.compile!
end.pretty_print
```
=> Optimize Grape::Path -> Reduce Hash Allocation

.github/workflows/danger.yml, .github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb, spec/grape/middleware/exception_spec.rb
This PR adds ruby 3.4 to the CI workflows. Some specs have been adjusted.
Merry 🎄
=> Add ruby 3.4 to CI

CHANGELOG.md, README.md
- Fixed typos found in `README.md` using the `typo_checker scan .` command with the [typo_checker](https://github.com/datpmt/typo_checker) Ruby gem.
- [### Custom Validation messages](https://github.com/ruby-grape/grape?tab=readme-ov-file#custom-validation-messages)
- Should replace `atleast` with `at least`.
- [## Describing and Inspecting an API](https://github.com/ruby-grape/grape?tab=readme-ov-file#describing-and-inspecting-an-api)
- Should replace `specifing` with `specifying`.
- I recommend using the [typocop GitHub Action](https://github.com/datpmt/typocop) to automatically check for typos in future pull requests.
=> Fixed typo in README

CHANGELOG.md, lib/grape/middleware/versioner/accept_version_header.rb, lib/grape/validations/validators/allow_blank_validator.rb, lib/grape/validations/validators/regexp_validator.rb, lib/grape/validations/validators/values_validator.rb, spec/grape/middleware/versioner/accept_version_header_spec.rb, spec/grape/validations/validators/allow_blank_validator_spec.rb, spec/grape/validations/validators/regexp_validator_spec.rb, spec/grape/validations/validators/values_validator_spec.rb
Fix #2523
It fixes the `allow_blank`, `regexp` and `values` validator.
It also covers the `Accept-Version` http header.
=> Validators bad encoding

CHANGELOG.md, lib/grape/middleware/error.rb, spec/grape/endpoint_spec.rb
Following this [comment](https://github.com/ruby-grape/grape/issues/2527#issuecomment-2625351197), this PR fixes the issue with the endpoint's status when not invoking `error!` through a block or a helper.
=> Force endpoint status in error_response and error!

CHANGELOG.md, lib/grape/api.rb, lib/grape/endpoint.rb, lib/grape/middleware/stack.rb, lib/grape/request.rb
This PR will delegate some functions to some inner objects. Here are the details:
Add delegation to `base_instance` and `instance_for_rack`
Use `delegate_missing_to` instead of method_missing functions
Delegate `params` and `headers` to `request`
Remove `LazyObject` for `build_headers` since its not forced 
Use `each_header` from Rack::Request instead of `env.each_pair`
Remove `.to_s` since Ruby 2.7 added `start_with?` to symbols
Delegates some functions
=> Delegates calls to inner object is some classes by extends Forwardable

CHANGELOG.md, lib/grape/api.rb, spec/grape/api_spec.rb
#2529 change the `@setup` variable to an [] but the code is using `+=` when adding a new step. This creates a new `[]` everytime and its not the best in terms on memory footprint. This PR replaced the `+=` by `<<` to not create new arrays.
I had to remove a [test](https://github.com/ruby-grape/grape/blob/45abe0dd9f18fcc0e1993b1d5a2988135cb216e1/spec/grape/api_spec.rb#L1703-L1705) since having duplicates is expected. It would have failed in #2529 if the test had been like this since @setup is not the same object.
```ruby
it 'does not unnecessarily retain duplicate setup blocks' do
subject.logger
first_setup = subject.instance_variable_get(:@setup)
subject.logger
last_setup = subject.instance_variable_get(:@setup)
expect(first_setup.size).to eq(last_setup.size)
end
```
Running …
=> Reduce array alloc on mount

CHANGELOG.md, lib/grape/middleware/stack.rb, spec/grape/api_spec.rb
This PR fix #2544. It adds the `ruby2_keyword_hash` flag dynamically since its serialized in the `namespace_stackable`. Contrary to Rails, when calling `use`, `insert`, `insert_before`, its serializing the arguments and not calling the stack. Thus, `ruby2_keywords` have no meaning in Grape's stack.
=> Fix middleware with keywords

CHANGELOG.md, lib/grape/error_formatter/jsonapi.rb, lib/grape/parser/jsonapi.rb, spec/grape/middleware/exception_spec.rb, spec/grape/middleware/formatter_spec.rb
This PR removes code and specs related to jsonapi. Since [0.10.0](https://github.com/ruby-grape/grape/blob/master/CHANGELOG.md#0100-20141219), Grape's doesn't support jsonapi but there were still some code related to it.
=> Remove jsonapi related code

CHANGELOG.md, grape.gemspec
This PR set minimal active support to 6.1. We do not test 6.0 in the CI and I think its fair to drop it.
=> Drop active support 6.0

CHANGELOG.md, lib/grape/cookies.rb, lib/grape/dsl/inside_route.rb, lib/grape/endpoint.rb, lib/grape/request.rb, spec/grape/dsl/inside_route_spec.rb
This PR delegates `cookies` to Grape::Request like the actual `params` and `headers` are. Minor tweaks have been made in `Grape::Cookies`:
- Rack's cookies will be read only if the API calls cookies
- Response cookies management is now done with a Set instead of Hash containing `true`
- Uses Forwardable module
=> Delegate cookies management to Grape::Request

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint/declared_spec.rb
=> Fix declared_hash_attr when passed_params is not an Hash

CHANGELOG.md, lib/grape/exceptions/conflicting_types.rb, lib/grape/exceptions/invalid_parameters.rb, lib/grape/exceptions/too_deep_parameters.rb, lib/grape/locale/en.yml, lib/grape/middleware/base.rb, lib/grape/middleware/error.rb, lib/grape/middleware/formatter.rb, lib/grape/middleware/versioner/param.rb, lib/grape/request.rb, spec/grape/middleware/base_spec.rb, spec/grape/request_spec.rb
This PRs reduces potential query params parsing. Instead of calling `Rack::Utils.parse_nested_query(env[Rack::QUERY_STRING])` directly, Grape will call Rack's function [GET](https://github.com/rack/rack/blob/4f15e7b814922af79605be4b02c5b7c3044ba206/lib/rack/request.rb#L491) that does the same work but keeps the parsed version in `RACK_REQUEST_QUERY_HASH`. This way, parsing will be done at most once.
Also, it fixes #2488 and it comes with a tiny refactor in `Grape::Middleware::Formatter` including comments in the code. Finally, this PR adds a new function named `rack_request` that's create a instance of `Rack::Request` from `env` in `Grape::Middleware::Base`. `Grape::Middleware::Formatter` had already the equivalent but named `request`. This helps for calling `GET` in middlewares and I …
=> Less query params parsing

CHANGELOG.md, lib/grape/request.rb
The constant was introduced in 45abe0dd9f18fcc0e1993b1d5a2988135cb216e1 but is never referenced and hasn't been since its inception.
=> Remove unused `Request::DEFAULT_PARAMS_BUILDER` constant

.github/workflows/edge.yml, .github/workflows/test.yml, CHANGELOG.md
This PR will enable `frozen_string_literal` at Ruby's level when running CI. It's already done locally through the our Docker setup but I thought it would be great to also have it in the CI.
Inspired from this [gist](https://gist.github.com/fxn/bf4eed2505c76f4fca03ab48c43adc72#how-to-help)
=> enable_frozen_string_literal in CI

.github/workflows/test.yml, CHANGELOG.md, README.md, UPGRADING.md, docker/Dockerfile, lib/grape.rb, lib/grape/dsl/routing.rb, lib/grape/endpoint.rb, spec/grape/api_spec.rb, spec/integration/rails/mounting_spec.rb, spec/spec_helper.rb
This PR adds a linting feature that can activated through `Grape.config.lint = true` or `lint!` in a `Grape::Api`.
Suggested in this [comment](https://github.com/ruby-grape/grape/issues/2334#issuecomment-2795024096).
By design, Grape's CI has `Grape.config.lint = true`, so all specs calling an endpoint are linted.
=> New feature : linting

spec/support/cookie_jar.rb
Rack may add `Rack::MockResponse::Cookie` itself: https://github.com/rack/rack/pull/2327
=> Move spec-only helper class out of the rack namespace

lib/grape/api.rb, spec/support/cookie_jar.rb
=> Fix memory leak when using recognize_path inside Grape::API

.rubocop.yml, CHANGELOG.md, Gemfile, spec/grape/api_spec.rb, spec/support/integer_helpers.rb
Off the back of looking at using standard, had to run a few upgrades to get it to work, so porting these minor updates over.
Rspec and rubocop run on my local and _should_ also run well in the actions.
=> Upgrade rubocop to 1.75.8

CHANGELOG.md, lib/grape/endpoint.rb, lib/grape/middleware/error.rb, spec/grape/api_spec.rb, spec/grape/endpoint_spec.rb
This PR refactors the integration of endpoint helpers and error middleware in Grape, focusing on clarity, maintainability, and improved error handling. The changes are motivated by the need to simplify the endpoint lifecycle, ensure correct helper inclusion, and make error handling more robust and intuitive.
- **Endpoint Helpers Refactor:**
- Helpers are now included via  at endpoint initialization, ensuring they are available in the endpoint context without polluting the global scope.
- The lazy initialization logic is simplified, and the block handling for endpoints is made more explicit and robust.
- **Middleware Error Handling:**
- The dynamic inclusion of helpers in  is removed. Error handlers always been executed in the context of the endpoint.
- The error handler logic is updated …
=> Revisit endpoint helpers and Grape::Middleware::Error helpers

CHANGELOG.md, lib/grape/api.rb, lib/grape/api/instance.rb, lib/grape/dsl/routing.rb, spec/grape/dsl/routing_spec.rb
**Base**: `master`  
**Branch**: `fix_routes_memoization`
Ensure `routes` memoization works reliably by making `routes` a non-overridable method and tightening specs to verify the memoization behavior directly.
- The `routes` method was eligible to be overridden, which could inadvertently break memoization and force repeated route computation.
- This PR safeguards memoization and updates tests to validate the behavior without relying on private implementation details.
- Make `routes` non-overridable to preserve memoization guarantees.
- Improve specs so they assert actual memoization effects rather than depending on private methods.
- Commit(s):
- 017e762c — Add `routes` as a non overridable methods so that memoization works properly. Added a better specs so that a private method is not …
=> Fix routes memoization

.github/workflows/test.yml, .rubocop.yml, .simplecov, CHANGELOG.md, gemfiles/rack_3_2.gemfile, lib/grape/dsl/desc.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/parameters.rb, lib/grape/dsl/request_response.rb, lib/grape/dsl/routing.rb, lib/grape/dsl/settings.rb, lib/grape/endpoint.rb, lib/grape/util/inheritable_setting.rb, spec/grape/api_spec.rb, spec/grape/dsl/inside_route_spec.rb, spec/grape/dsl/parameters_spec.rb, spec/grape/dsl/request_response_spec.rb
This PR adds support for testing Grape with Rack 3.2.x versions by introducing a new gemfile and updating the CI workflow to include it in the test matrix.
- **New gemfile**: `gemfiles/rack_3_2.gemfile` - Tests compatibility with Rack ~> 3.2
- **CI integration**: Updated `.github/workflows/test.yml` to include `rack_3_2.gemfile` in the test matrix
- **GitHub Actions workflow**: Extended the test matrix to include the new Rack 3.2 gemfile alongside existing Rack versions (2.0, 3.0, 3.1)
The changes ensure that Grape is tested against Rack 3.2.x versions across all supported Ruby versions (3.0, 3.1, 3.2, 3.3, 3.4). This maintains backward compatibility while ensuring forward compatibility with the latest Rack releases.
- **No breaking changes**: This is purely additive - existing …
=> Add Rack 3.2 Support
