ruby-grape/grape

README.md
https://groups.google.com/forum/#!topic/ruby-grape/4h-361pidc4
Thanks again for the wonderful library. If there's anything I can do to improve this PR, please let me know.
=> Update README.md to include MiniTest Examples

UPGRADING.md
Please refer https://github.com/intridea/grape/issues/898. Thanks!
=> add docs for version method behavior change

lib/grape/middleware/versioner/header.rb
Minor typo in method definition commends
=> Fixes typo in code comments

README.md
For me, this way is a bit clearer.
=> Adds a parameter in the doc for allow_blank.

LICENSE, README.md
Made 2 changes:
1) Modified LICENSE to include the latest year as a year-range.
2) Modified README.md's copyright section to include the latest year.
No other files were changed.
=> Update info in readme and license

lib/grape/api.rb, lib/grape/dsl/helpers.rb, lib/grape/dsl/parameters.rb, lib/grape/http/request.rb, lib/grape/middleware/versioner/header.rb
Inspired by [avoid run time allocations](https://github.com/wonderbread/rack-pratchett/commit/dcbe15d604f5464fa64f775f411598d81d61c1df), and [fasterer] (https://github.com/DamirSvrtan/fasterer)
=> make it faster and avoid run time allocations

grape.gemspec
I guess the title explains itself.
=> Add a space

lib/grape/dsl/helpers.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/request_response.rb, lib/grape/dsl/routing.rb
Tiding up comments according to general guidelines, let's be perfectionists. :)
=> Format comments

lib/grape/error_formatter/json.rb
Fixes https://github.com/intridea/grape/commit/c20a9ad3ff81865898258d8bf92271048f1ff2b0#commitcomment-10545892
Not sure if correct response is to open PR or append to previous. Let me know preferred method.
=> Remove extra whitespace.

CHANGELOG.md, lib/grape/dsl/configuration.rb, lib/grape/dsl/validations.rb, spec/grape/api_spec.rb, spec/grape/dsl/validations_spec.rb
=> Reset description[:params] when resetting validations

benchmark/simple.rb
This is the benchmark I used to test changes in #1110 and #1111.
I also plan to add here more different benchmarks that cover all the features of Grape.
=> Add simple benchmark.

.travis.yml
More info here: http://docs.travis-ci.com/user/migrating-from-legacy/
=> Set sudo: false for running tests in containers

lib/grape.rb, lib/grape/request.rb, lib/grape/util/env.rb, spec/grape/request_spec.rb
...And remove some cryptic regexp stuff from headers construction.
New algorithm is easier to read and also faster.
=> Optimize construction of headers.

README.md
in response to #1117. Please verify the changes! The "HTTP Status Code" move as pointed out is definitely needed.
=> README formatting (indentation), organizational, and TOC cleanup

CHANGELOG.md, code_of_conduct.md
Based on: http://contributor-covenant.org/
=> Adds a code of conduct.

.rubocop_todo.yml, lib/grape/endpoint.rb
This PR follows the same logic as https://github.com/ruby-grape/grape/pull/1201.
=> Memoize endpoint helpers.

CHANGELOG.md
=> Fix Release date of 0.14.0 in Changelog

spec/grape/api_spec.rb
=> Unspecified extension should be included in format parameter

spec/grape/api/invalid_format_spec.rb
=> Spec for #1276.

CHANGELOG.md
=> Add a section about #1326

CHANGELOG.md, grape.gemspec, lib/grape.rb, lib/grape/error_formatter.rb, lib/grape/formatter.rb, lib/grape/parser.rb, lib/grape/util/registrable.rb, spec/grape/parser_spec.rb
=> Update some points, ref #1330

CHANGELOG.md
removed in 9f4ba67d4aca90f04a65c5ff921b1687942eb99c
=> add removed a section divider in CHANGELOG.md

README.md
Inspired by https://twitter.com/buka_gor/status/689036018708799492
PS. It's really hard to call grape a micro-framework (no matter how hard you try).
=> README-FIX: Grape is not a micro-framework

.rubocop_todo.yml, lib/grape/endpoint.rb
Thought I might start addressing the violations in `.rubocop_todo.yml`
=> fixed guard clause violation

Dangerfile
=> Remove the is trivial reference in the Dangerfile correctly

CHANGELOG.md, Dangerfile
Use Danger to check CHANGELOG format.
=> Check CHANGELOG format.

CHANGELOG.md, Dangerfile, Gemfile
This is WIP, requires next version of danger and a release of ruby-grape-danger.
https://github.com/danger/danger/pull/504
https://github.com/danger/danger/pull/507
https://github.com/ruby-grape/danger/pull/5
=> Use the ruby-grape-danger gem.

README.md
=> Add information about #mount inheritance

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
fixes https://github.com/ruby-grape/grape/issues/1584
=> fix some include_missing bugs in declared

README.md
@dblock here goes the update to the README file.
=> Update README according to new `helpers` macro interface

CHANGELOG.md, lib/grape/dsl/inside_route.rb, spec/grape/endpoint_spec.rb
=> use correct params class in declared method

spec/grape/dsl/helpers_spec.rb
Replace https://github.com/ruby-grape/grape/pull/1618
Also LeeT
=> Added test for `use`

README.md
I don't know if it's the Rails way, but it's working for me.
=> Update code reloading example for Rails 5.1.4

.travis.yml
Especially rbx-2 was not tested in last passed CI https://travis-ci.org/ruby-grape/grape/jobs/286558293
=> Update rubies in CI

README.md
Adjust code block style in README.
=> Add white space between brackets

Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_3.gemfile, gemfiles/rails_4.gemfile, gemfiles/rails_5.gemfile, gemfiles/rails_edge.gemfile
=> Use coveralls-reborn for rails-edge.

README.md
Was skimming thru the README and this minor thing caught my eye an started to bug me :)
=> Minor readme fix for the basic usage example

README.md
Official Grape support was merged and released last Tuesday as version 3.2.0 🎉
=> Add ElasticAPM to Monitoring products list

.gitignore
ref https://github.com/ruby-grape/grape/pull/1956/files#diff-93830fa29d616f7c87903d08b5b1b29aR40
=> ignore .rspec_status

CHANGELOG.md, lib/grape.rb, lib/grape/dsl/request_response.rb, lib/grape/dsl/settings.rb, lib/grape/endpoint.rb, lib/grape/util/inheritable_setting.rb, lib/grape/util/reverse_stackable_values.rb, lib/grape/util/stackable_values.rb, lib/grape/validations/attributes_iterator.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/types/build_coercer.rb, spec/grape/api/instance_spec.rb, spec/grape/api_spec.rb, spec/grape/dsl/request_response_spec.rb, spec/grape/util/inheritable_setting_spec.rb, spec/grape/util/reverse_stackable_values_spec.rb, spec/grape/util/stackable_values_spec.rb
Reverts ruby-grape/grape#1953
Includes #1959
=> Revert "delete a reversible stackable values class"

lib/grape/dsl/settings.rb, lib/grape/util/stackable_values.rb, lib/grape/validations/params_scope.rb, lib/grape/validations/types/build_coercer.rb, spec/grape/api/instance_spec.rb
=> Re-apply the micro-optimizations and parent fix from #1961.

CHANGELOG.md
=> Fix pull request reference in CHANGELOG.md

.travis.yml, Appraisals, CHANGELOG.md, gemfiles/rails_6.gemfile
I updated Rails version to 5.2 and I added Rails 6.0 to travis
=> Update rails versions appraisal

UPGRADING.md
This pattern wasn't documented, but it was all over our codebase, which means we probably saw it online somewhere and it worked fine.
Adding a note to upgrading guide for future readers (/future me) trying to debug tests breaking in this update.
=> Add note about an undocumented regression in bool coercion

.github/workflows/danger.yml, README.md
=> Updated Danger token

CHANGELOG.md, lib/grape/api.rb, lib/grape/dsl/callbacks.rb, lib/grape/dsl/inside_route.rb, lib/grape/dsl/parameters.rb, lib/grape/dsl/routing.rb, lib/grape/exceptions/validation.rb, spec/grape/entity_spec.rb
Just some spelling corrections
=> Spelling corrections

CHANGELOG.md, lib/grape/api/instance.rb, spec/grape/api_spec.rb
Fixes: https://github.com/ruby-grape/grape/issues/2175
Originally generated here: Coming from this PR: #1263 by trying to address an issue with wilcard matching
=> Fixes ISSUE-2175 - Options call failing if matching all routes

README.md
This PR updates readme for registering a new middleware in custom Rails applications as discussed in issue #2182
=> Update readme about registering middleware in custom Rails applications

README.md
=> Update README.md about values validator used with allow_blank

Appraisals, gemfiles/rack2.gemfile, gemfiles/rails_6.gemfile
=> Fix versions in rack2 and rails6 file

CHANGELOG.md, lib/grape/dsl/parameters.rb, spec/grape/validations_spec.rb
=> support kwargs in shared params definition

.github/workflows/danger.yml
All tokens belonging to @grape-bot have been rotated by GitHub :(
=> Rotate Danger token.

CHANGELOG.md, Gemfile, gemfiles/multi_json.gemfile, gemfiles/multi_xml.gemfile, gemfiles/rack_1_0.gemfile, gemfiles/rack_2_0.gemfile, gemfiles/rack_3_0.gemfile, gemfiles/rack_edge.gemfile, gemfiles/rails_5_2.gemfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, gemfiles/rails_edge.gemfile
=> Remove maruku and rubocop-ast as dependencies

CHANGELOG.md, spec/support/deprecated_warning_handlers.rb
Fix #2409 but #2405 must be merged first
=> Add DeprecationWarning to handle gems deprecations in a best effort

.github/workflows/test.yml, CHANGELOG.md, gemfiles/rails_7_2.gemfile
This PR adds Rails 7.2 in the CI Workflow
=> Add Rails 7.2 in CI workflow

.github/workflows/test.yml, CHANGELOG.md, gemfiles/rails_6_0.gemfile, gemfiles/rails_8_0.gemfile
This PR adds Rails 8.0 and removes Rails 6.0 in the CI test matrix
=> Add Rails 8.0 gemfile

.github/FUNDING.yml
Tidelift is now part of Sonar and is paywalled with sales all over the website. Adding myself directly to funding, any active maintainer (e.g. @ericproulx) should feel free to do the same. Will leave this open for a few days for any objections or comments, then merge.
=> Added myself to FUNDING.
